import type { KnipConfig } from "knip"

const isProductionMode = process.argv.includes("--production")

const testingEntryPoints = [
  // Vitest globs for these; declare them so their exports are not reported.
  "src/**/*.test.{js,ts,jsx,tsx}",
  "src/test/**/*.{js,ts,jsx,tsx}",
]

const sharedEntryPoints = [
  // shadcn/ui components are a shared component library; all of their exports
  // are public API and must not be reported as dead code.
  "src/components/ui/**/*.{js,jsx,ts,tsx}!",
]

const config: KnipConfig = {
  workspaces: {
    ".": {
      // The root is a Bun workspace manager; it owns no source files.
      entry: [],
      project: [],
    },
    frontend: {
      entry: [...testingEntryPoints, ...sharedEntryPoints],
      project: [
        "src/**/*.{js,jsx,ts,tsx,css}!",
        // Generated by @hey-api/openapi-ts and the TanStack Router plugin.
        "!src/client/**",
        "!src/routeTree.gen.ts",
      ],
      ignoreDependencies: isProductionMode
        ? [
            // Consumed by the Vite plugin config, which is not production code.
            "@tailwindcss/vite",
          ]
        : [],
    },
    "packages/react-email": {
      entry: ["emails/**/*.tsx!"],
      project: ["**/*.{js,jsx,ts,tsx}!"],
      // The plugin registers non-production entries that collide with the
      // production entry above; entries are declared explicitly instead.
      "react-email": false,
      ignoreDependencies: isProductionMode
        ? [
            // Used by the react-email build/preview tooling, not imported by emails.
            "react-dom",
            "react-email",
          ]
        : [],
    },
  },
  ignoreExportsUsedInFile: isProductionMode,
  rules: {
    binaries: "off",
    enumMembers: "off",
  },
  include: ["nsExports", "nsTypes"],
  treatConfigHintsAsErrors: true,
  treatTagHintsAsErrors: true,
}

export default config
