// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ActivitiesPublic
 *
 * List of activity events.
 */
export type ActivitiesPublic = {
    /**
     * Data
     */
    data: Array<ActivityPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ActivityKind
 *
 * Kinds of activity recorded in the feed.
 */
export type ActivityKind = 'star' | 'watch' | 'fork' | 'issue_open' | 'issue_close' | 'issue_reopen' | 'comment' | 'pull_request_open' | 'pull_request_merge' | 'pull_request_close' | 'pull_request_reopen' | 'release';

/**
 * ActivityPublic
 *
 * Public activity representation.
 */
export type ActivityPublic = {
    /**
     * Id
     */
    id: string;
    kind: ActivityKind;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Actor Username
     */
    actor_username: string;
    /**
     * Repo Owner
     */
    repo_owner?: string | null;
    /**
     * Repo Name
     */
    repo_name?: string | null;
    target_type?: ActivityTargetType | null;
    /**
     * Target Number
     */
    target_number?: number | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ActivityTargetType
 *
 * Types of targets an activity event can reference.
 */
export type ActivityTargetType = 'repository' | 'issue' | 'pull_request' | 'release';

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * BranchInfo
 *
 * Information about a branch.
 */
export type BranchInfo = {
    /**
     * Name
     */
    name: string;
    /**
     * Is Default
     */
    is_default: boolean;
};

/**
 * CommentCreate
 *
 * Request to create a comment.
 */
export type CommentCreate = {
    /**
     * Body
     */
    body: string;
};

/**
 * CommentPublic
 *
 * Public comment representation.
 */
export type CommentPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Author Username
     */
    author_username: string;
    /**
     * Body
     */
    body: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * CommentUpdate
 *
 * Request to update a comment.
 */
export type CommentUpdate = {
    /**
     * Body
     */
    body: string;
};

/**
 * CommentsPublic
 *
 * List of comments.
 */
export type CommentsPublic = {
    /**
     * Data
     */
    data: Array<CommentPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * CommitChangeType
 *
 * How a file changed within a commit.
 */
export type CommitChangeType = 'add' | 'modify' | 'delete' | 'rename';

/**
 * CommitDetail
 *
 * Detailed information about a single commit.
 */
export type CommitDetail = {
    /**
     * Sha
     */
    sha: string;
    /**
     * Message
     */
    message: string;
    /**
     * Author
     */
    author: string;
    /**
     * Author Email
     */
    author_email: string;
    /**
     * Timestamp
     */
    timestamp: number;
    /**
     * Parents
     */
    parents: Array<string>;
    /**
     * Files
     */
    files: Array<CommitFileChange>;
    /**
     * Additions
     */
    additions: number;
    /**
     * Deletions
     */
    deletions: number;
};

/**
 * CommitFileChange
 *
 * A file changed by a commit, with its unified diff.
 */
export type CommitFileChange = {
    /**
     * Path
     */
    path: string;
    /**
     * Old Path
     */
    old_path?: string | null;
    change_type: CommitChangeType;
    /**
     * Additions
     */
    additions: number;
    /**
     * Deletions
     */
    deletions: number;
    /**
     * Patch
     */
    patch: string;
};

/**
 * CommitInfo
 *
 * Information about a commit.
 */
export type CommitInfo = {
    /**
     * Sha
     */
    sha: string;
    /**
     * Message
     */
    message: string;
    /**
     * Author
     */
    author: string;
    /**
     * Timestamp
     */
    timestamp: number;
};

/**
 * CommitListItem
 *
 * A single commit in a repository's history.
 */
export type CommitListItem = {
    /**
     * Sha
     */
    sha: string;
    /**
     * Message
     */
    message: string;
    /**
     * Author
     */
    author: string;
    /**
     * Author Email
     */
    author_email: string;
    /**
     * Timestamp
     */
    timestamp: number;
};

/**
 * CommitsPublic
 *
 * A page of commit history.
 */
export type CommitsPublic = {
    /**
     * Data
     */
    data: Array<CommitListItem>;
    /**
     * Count
     */
    count: number;
    /**
     * Ref
     */
    ref: string;
};

/**
 * CompareResult
 *
 * The files changed between two refs, e.g. a pull request's base and head.
 */
export type CompareResult = {
    /**
     * Base Commit
     */
    base_commit?: string | null;
    /**
     * Head Commit
     */
    head_commit?: string | null;
    /**
     * Files
     */
    files: Array<CommitFileChange>;
    /**
     * Additions
     */
    additions: number;
    /**
     * Deletions
     */
    deletions: number;
};

/**
 * CreateRepositoryRequest
 *
 * Request to create a new repository.
 */
export type CreateRepositoryRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Owner
     */
    owner: string;
};

/**
 * FileContent
 *
 * File content with syntax highlighting.
 */
export type FileContent = {
    /**
     * Name
     */
    name: string;
    /**
     * Path
     */
    path: string;
    /**
     * Size
     */
    size: number;
    /**
     * Content
     */
    content: string;
    /**
     * Highlighted Html
     */
    highlighted_html: string;
    /**
     * Css
     */
    css: string;
    /**
     * Css Dark
     */
    css_dark: string;
    /**
     * Language
     */
    language: string;
    /**
     * Line Count
     */
    line_count: number;
};

/**
 * ForkCreate
 *
 * Request to fork a repository.
 */
export type ForkCreate = {
    /**
     * Owner
     */
    owner?: string | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ForkPublic
 *
 * Public representation of a fork.
 */
export type ForkPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Owner
     */
    owner: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Stars Count
     */
    stars_count?: number;
    /**
     * Forks Count
     */
    forks_count?: number;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ForksPublic
 *
 * List of forks for a repository.
 */
export type ForksPublic = {
    /**
     * Data
     */
    data: Array<ForkPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IssueCreate
 *
 * Request to create a new issue.
 */
export type IssueCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Body
     */
    body?: string | null;
};

/**
 * IssuePublic
 *
 * Public issue representation.
 */
export type IssuePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Repo Owner
     */
    repo_owner: string;
    /**
     * Repo Name
     */
    repo_name: string;
    /**
     * Number
     */
    number: number;
    /**
     * Title
     */
    title: string;
    /**
     * Body
     */
    body?: string | null;
    state: IssueState;
    /**
     * Author Username
     */
    author_username: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * IssueState
 *
 * State of an issue or pull request.
 */
export type IssueState = 'open' | 'closed' | 'merged';

/**
 * IssueUpdate
 *
 * Request to update an issue.
 */
export type IssueUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Body
     */
    body?: string | null;
    state?: IssueState | null;
};

/**
 * IssuesListPublic
 *
 * List of issues.
 */
export type IssuesListPublic = {
    /**
     * Data
     */
    data: Array<IssuePublic>;
    /**
     * Count
     */
    count: number;
    /**
     * Open Count
     */
    open_count: number;
    /**
     * Closed Count
     */
    closed_count: number;
};

/**
 * NewPassword
 *
 * Schema for password reset with token.
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * OrganizationCreate
 *
 * Request to create a new organization.
 */
export type OrganizationCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * OrganizationPublic
 *
 * Public organization representation.
 */
export type OrganizationPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * OrganizationsPublic
 *
 * List of organizations.
 */
export type OrganizationsPublic = {
    /**
     * Data
     */
    data: Array<OrganizationPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * PrincipalType
 *
 * The kind of principal.
 */
export type PrincipalType = 'user' | 'organization';

/**
 * PrivateUserCreate
 *
 * Schema for creating a user via private API.
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * ProfilePublic
 *
 * Public profile for a principal (user or organization).
 */
export type ProfilePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Display Name
     */
    display_name?: string | null;
    principal_type: PrincipalType;
};

/**
 * PullRequestCreate
 *
 * Request to create a new pull request.
 */
export type PullRequestCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Body
     */
    body?: string | null;
    /**
     * Head Branch
     */
    head_branch: string;
    /**
     * Base Branch
     */
    base_branch?: string;
};

/**
 * PullRequestPublic
 *
 * Public pull request representation.
 */
export type PullRequestPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Repo Owner
     */
    repo_owner: string;
    /**
     * Repo Name
     */
    repo_name: string;
    /**
     * Number
     */
    number: number;
    /**
     * Title
     */
    title: string;
    /**
     * Body
     */
    body?: string | null;
    state: IssueState;
    /**
     * Head Branch
     */
    head_branch: string;
    /**
     * Base Branch
     */
    base_branch: string;
    /**
     * Author Username
     */
    author_username: string;
    /**
     * Merge Base
     */
    merge_base?: string | null;
    /**
     * Merged Commit Id
     */
    merged_commit_id?: string | null;
    /**
     * Has Merged
     */
    has_merged?: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * PullRequestUpdate
 *
 * Request to update a pull request.
 */
export type PullRequestUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Body
     */
    body?: string | null;
    state?: IssueState | null;
};

/**
 * PullRequestsListPublic
 *
 * List of pull requests.
 */
export type PullRequestsListPublic = {
    /**
     * Data
     */
    data: Array<PullRequestPublic>;
    /**
     * Count
     */
    count: number;
    /**
     * Open Count
     */
    open_count: number;
    /**
     * Closed Count
     */
    closed_count: number;
};

/**
 * ReadmeContent
 *
 * README file content.
 */
export type ReadmeContent = {
    /**
     * Filename
     */
    filename: string;
    /**
     * Content
     */
    content: string;
    /**
     * Html
     */
    html: string;
};

/**
 * ReleaseCreate
 *
 * Request to create a release.
 */
export type ReleaseCreate = {
    /**
     * Tag Name
     */
    tag_name: string;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Body
     */
    body?: string | null;
    /**
     * Target Commitish
     */
    target_commitish?: string;
    /**
     * Is Draft
     */
    is_draft?: boolean;
    /**
     * Is Prerelease
     */
    is_prerelease?: boolean;
};

/**
 * ReleasePublic
 *
 * Public release representation.
 */
export type ReleasePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Repo Owner
     */
    repo_owner: string;
    /**
     * Repo Name
     */
    repo_name: string;
    /**
     * Tag Name
     */
    tag_name: string;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Body
     */
    body?: string | null;
    /**
     * Target Commitish
     */
    target_commitish?: string;
    /**
     * Is Draft
     */
    is_draft?: boolean;
    /**
     * Is Prerelease
     */
    is_prerelease?: boolean;
    /**
     * Author Username
     */
    author_username: string;
    /**
     * Published At
     */
    published_at?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ReleaseUpdate
 *
 * Request to update a release.
 */
export type ReleaseUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Body
     */
    body?: string | null;
    /**
     * Is Draft
     */
    is_draft?: boolean | null;
    /**
     * Is Prerelease
     */
    is_prerelease?: boolean | null;
};

/**
 * ReleasesPublic
 *
 * List of releases.
 */
export type ReleasesPublic = {
    /**
     * Data
     */
    data: Array<ReleasePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * RepositoriesPublic
 *
 * List of repositories.
 */
export type RepositoriesPublic = {
    /**
     * Data
     */
    data: Array<Repository>;
    /**
     * Count
     */
    count: number;
};

/**
 * Repository
 *
 * Repository schema.
 */
export type Repository = {
    /**
     * Name
     */
    name: string;
    /**
     * Owner
     */
    owner: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Default Branch
     */
    default_branch?: string;
    /**
     * Is Private
     */
    is_private?: boolean;
    /**
     * Stars Count
     */
    stars_count?: number;
    /**
     * Forks Count
     */
    forks_count?: number;
    /**
     * Watchers Count
     */
    watchers_count?: number;
    /**
     * Fork Of
     */
    fork_of?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * RepositoryInfo
 *
 * Extended repository information with metadata.
 */
export type RepositoryInfo = {
    /**
     * Name
     */
    name: string;
    /**
     * Owner
     */
    owner: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Private
     */
    is_private?: boolean;
    /**
     * Default Branch
     */
    default_branch: string;
    /**
     * Branch Count
     */
    branch_count: number;
    /**
     * Tag Count
     */
    tag_count: number;
    /**
     * Stars Count
     */
    stars_count?: number;
    /**
     * Forks Count
     */
    forks_count?: number;
    /**
     * Watchers Count
     */
    watchers_count?: number;
    /**
     * Fork Of
     */
    fork_of?: string | null;
    last_commit?: CommitInfo | null;
};

/**
 * StarState
 *
 * Whether the current user starred a repository, and the total count.
 */
export type StarState = {
    /**
     * Is Starred
     */
    is_starred: boolean;
    /**
     * Stars Count
     */
    stars_count: number;
};

/**
 * StargazersPublic
 *
 * List of users who starred a repository.
 */
export type StargazersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * TagInfo
 *
 * Information about a Git tag.
 */
export type TagInfo = {
    /**
     * Name
     */
    name: string;
    /**
     * Commit Sha
     */
    commit_sha: string;
    /**
     * Timestamp
     */
    timestamp?: number | null;
};

/**
 * TagsPublic
 *
 * List of Git tags.
 */
export type TagsPublic = {
    /**
     * Data
     */
    data: Array<TagInfo>;
    /**
     * Count
     */
    count: number;
};

/**
 * Token
 *
 * OAuth2 token response schema.
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * TreeEntry
 *
 * A single entry in a Git tree (file or directory).
 */
export type TreeEntry = {
    /**
     * Name
     */
    name: string;
    /**
     * Path
     */
    path: string;
    type: TreeEntryType;
    /**
     * Size
     */
    size?: number | null;
};

/**
 * TreeEntryType
 *
 * Type of a Git tree entry.
 */
export type TreeEntryType = 'tree' | 'blob';

/**
 * TreeListing
 *
 * Directory listing for a repository path.
 */
export type TreeListing = {
    /**
     * Entries
     */
    entries: Array<TreeEntry>;
    /**
     * Tree Path
     */
    tree_path: string;
    /**
     * Ref
     */
    ref: string;
};

/**
 * UpdatePassword
 *
 * Schema for password update.
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 *
 * Schema for creating a new user.
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 *
 * Schema for returning user data to clients.
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
};

/**
 * UserRegister
 *
 * Schema for user self-registration.
 */
export type UserRegister = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserUpdate
 *
 * Schema for updating a user (admin).
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 *
 * Schema for users updating their own profile.
 */
export type UserUpdateMe = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 *
 * Schema for paginated list of users.
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WatcherState
 *
 * Whether the current user watches a repository, and the total count.
 */
export type WatcherState = {
    /**
     * Is Watching
     */
    is_watching: boolean;
    /**
     * Watchers Count
     */
    watchers_count: number;
};

/**
 * WatchersPublic
 *
 * List of users watching a repository.
 */
export type WatchersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type gitGetInfoRefsData = {
    body?: never;
    path: {
        /**
         * Repo Path
         */
        repo_path: string;
    };
    query?: never;
    url: '/api/v1/{repo_path}/info/refs';
};

export type gitGetInfoRefsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type gitGetInfoRefsError = gitGetInfoRefsErrors[keyof gitGetInfoRefsErrors];

export type gitGetInfoRefsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type gitGetHeadData = {
    body?: never;
    path: {
        /**
         * Repo Path
         */
        repo_path: string;
    };
    query?: never;
    url: '/api/v1/{repo_path}/HEAD';
};

export type gitGetHeadErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type gitGetHeadError = gitGetHeadErrors[keyof gitGetHeadErrors];

export type gitGetHeadResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type gitGetInfoPacksData = {
    body?: never;
    path: {
        /**
         * Repo Path
         */
        repo_path: string;
    };
    query?: never;
    url: '/api/v1/{repo_path}/objects/info/packs';
};

export type gitGetInfoPacksErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type gitGetInfoPacksError = gitGetInfoPacksErrors[keyof gitGetInfoPacksErrors];

export type gitGetInfoPacksResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type gitGetLooseObjectData = {
    body?: never;
    path: {
        /**
         * Repo Path
         */
        repo_path: string;
        /**
         * Prefix
         */
        prefix: string;
        /**
         * Suffix
         */
        suffix: string;
    };
    query?: never;
    url: '/api/v1/{repo_path}/objects/{prefix}/{suffix}';
};

export type gitGetLooseObjectErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type gitGetLooseObjectError = gitGetLooseObjectErrors[keyof gitGetLooseObjectErrors];

export type gitGetLooseObjectResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type gitGetPackFileData = {
    body?: never;
    path: {
        /**
         * Repo Path
         */
        repo_path: string;
        /**
         * Pack File
         */
        pack_file: string;
    };
    query?: never;
    url: '/api/v1/{repo_path}/objects/pack/{pack_file}';
};

export type gitGetPackFileErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type gitGetPackFileError = gitGetPackFileErrors[keyof gitGetPackFileErrors];

export type gitGetPackFileResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type gitGitUploadPackData = {
    body?: never;
    path: {
        /**
         * Repo Path
         */
        repo_path: string;
    };
    query?: never;
    url: '/api/v1/{repo_path}/git-upload-pack';
};

export type gitGitUploadPackErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type gitGitUploadPackError = gitGitUploadPackErrors[keyof gitGitUploadPackErrors];

export type gitGitUploadPackResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type gitGitReceivePackData = {
    body?: never;
    path: {
        /**
         * Repo Path
         */
        repo_path: string;
    };
    query?: never;
    url: '/api/v1/{repo_path}/git-receive-pack';
};

export type gitGitReceivePackErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type gitGitReceivePackError = gitGitReceivePackErrors[keyof gitGitReceivePackErrors];

export type gitGitReceivePackResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type organizationsListOrganizationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/organizations/';
};

export type organizationsListOrganizationsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type organizationsListOrganizationsError = organizationsListOrganizationsErrors[keyof organizationsListOrganizationsErrors];

export type organizationsListOrganizationsResponses = {
    /**
     * Successful Response
     */
    200: OrganizationsPublic;
};

export type organizationsListOrganizationsResponse = organizationsListOrganizationsResponses[keyof organizationsListOrganizationsResponses];

export type organizationsCreateOrganizationData = {
    body: OrganizationCreate;
    path?: never;
    query?: never;
    url: '/api/v1/organizations/';
};

export type organizationsCreateOrganizationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type organizationsCreateOrganizationError = organizationsCreateOrganizationErrors[keyof organizationsCreateOrganizationErrors];

export type organizationsCreateOrganizationResponses = {
    /**
     * Successful Response
     */
    201: OrganizationPublic;
};

export type organizationsCreateOrganizationResponse = organizationsCreateOrganizationResponses[keyof organizationsCreateOrganizationResponses];

export type starsUnstarRepositoryData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
    };
    query?: never;
    url: '/api/v1/repositories/{owner}/{repo}/star';
};

export type starsUnstarRepositoryErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type starsUnstarRepositoryError = starsUnstarRepositoryErrors[keyof starsUnstarRepositoryErrors];

export type starsUnstarRepositoryResponses = {
    /**
     * Successful Response
     */
    200: StarState;
};

export type starsUnstarRepositoryResponse = starsUnstarRepositoryResponses[keyof starsUnstarRepositoryResponses];

export type starsGetStarStateData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
    };
    query?: never;
    url: '/api/v1/repositories/{owner}/{repo}/star';
};

export type starsGetStarStateErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type starsGetStarStateError = starsGetStarStateErrors[keyof starsGetStarStateErrors];

export type starsGetStarStateResponses = {
    /**
     * Successful Response
     */
    200: StarState;
};

export type starsGetStarStateResponse = starsGetStarStateResponses[keyof starsGetStarStateResponses];

export type starsStarRepositoryData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
    };
    query?: never;
    url: '/api/v1/repositories/{owner}/{repo}/star';
};

export type starsStarRepositoryErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type starsStarRepositoryError = starsStarRepositoryErrors[keyof starsStarRepositoryErrors];

export type starsStarRepositoryResponses = {
    /**
     * Successful Response
     */
    200: StarState;
};

export type starsStarRepositoryResponse = starsStarRepositoryResponses[keyof starsStarRepositoryResponses];

export type starsListStargazersData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
    };
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/repositories/{owner}/{repo}/stargazers';
};

export type starsListStargazersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type starsListStargazersError = starsListStargazersErrors[keyof starsListStargazersErrors];

export type starsListStargazersResponses = {
    /**
     * Successful Response
     */
    200: StargazersPublic;
};

export type starsListStargazersResponse = starsListStargazersResponses[keyof starsListStargazersResponses];

export type starsListStarredRepositoriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/me/starred';
};

export type starsListStarredRepositoriesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type starsListStarredRepositoriesError = starsListStarredRepositoriesErrors[keyof starsListStarredRepositoriesErrors];

export type starsListStarredRepositoriesResponses = {
    /**
     * Successful Response
     */
    200: RepositoriesPublic;
};

export type starsListStarredRepositoriesResponse = starsListStarredRepositoriesResponses[keyof starsListStarredRepositoriesResponses];

export type watchersUnwatchRepositoryData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
    };
    query?: never;
    url: '/api/v1/repositories/{owner}/{repo}/watch';
};

export type watchersUnwatchRepositoryErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type watchersUnwatchRepositoryError = watchersUnwatchRepositoryErrors[keyof watchersUnwatchRepositoryErrors];

export type watchersUnwatchRepositoryResponses = {
    /**
     * Successful Response
     */
    200: WatcherState;
};

export type watchersUnwatchRepositoryResponse = watchersUnwatchRepositoryResponses[keyof watchersUnwatchRepositoryResponses];

export type watchersGetWatchStateData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
    };
    query?: never;
    url: '/api/v1/repositories/{owner}/{repo}/watch';
};

export type watchersGetWatchStateErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type watchersGetWatchStateError = watchersGetWatchStateErrors[keyof watchersGetWatchStateErrors];

export type watchersGetWatchStateResponses = {
    /**
     * Successful Response
     */
    200: WatcherState;
};

export type watchersGetWatchStateResponse = watchersGetWatchStateResponses[keyof watchersGetWatchStateResponses];

export type watchersWatchRepositoryData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
    };
    query?: never;
    url: '/api/v1/repositories/{owner}/{repo}/watch';
};

export type watchersWatchRepositoryErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type watchersWatchRepositoryError = watchersWatchRepositoryErrors[keyof watchersWatchRepositoryErrors];

export type watchersWatchRepositoryResponses = {
    /**
     * Successful Response
     */
    200: WatcherState;
};

export type watchersWatchRepositoryResponse = watchersWatchRepositoryResponses[keyof watchersWatchRepositoryResponses];

export type watchersListWatchersData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
    };
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/repositories/{owner}/{repo}/watchers';
};

export type watchersListWatchersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type watchersListWatchersError = watchersListWatchersErrors[keyof watchersListWatchersErrors];

export type watchersListWatchersResponses = {
    /**
     * Successful Response
     */
    200: WatchersPublic;
};

export type watchersListWatchersResponse = watchersListWatchersResponses[keyof watchersListWatchersResponses];

export type forksListForksData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
    };
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/repositories/{owner}/{repo}/forks';
};

export type forksListForksErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type forksListForksError = forksListForksErrors[keyof forksListForksErrors];

export type forksListForksResponses = {
    /**
     * Successful Response
     */
    200: ForksPublic;
};

export type forksListForksResponse = forksListForksResponses[keyof forksListForksResponses];

export type forksForkRepositoryData = {
    body: ForkCreate;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
    };
    query?: never;
    url: '/api/v1/repositories/{owner}/{repo}/forks';
};

export type forksForkRepositoryErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type forksForkRepositoryError = forksForkRepositoryErrors[keyof forksForkRepositoryErrors];

export type forksForkRepositoryResponses = {
    /**
     * Successful Response
     */
    201: ForkPublic;
};

export type forksForkRepositoryResponse = forksForkRepositoryResponses[keyof forksForkRepositoryResponses];

export type commentsListCommentsData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
        /**
         * Number
         */
        number: number;
    };
    query?: never;
    url: '/api/v1/repositories/{owner}/{repo}/issues/{number}/comments';
};

export type commentsListCommentsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type commentsListCommentsError = commentsListCommentsErrors[keyof commentsListCommentsErrors];

export type commentsListCommentsResponses = {
    /**
     * Successful Response
     */
    200: CommentsPublic;
};

export type commentsListCommentsResponse = commentsListCommentsResponses[keyof commentsListCommentsResponses];

export type commentsCreateCommentData = {
    body: CommentCreate;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
        /**
         * Number
         */
        number: number;
    };
    query?: never;
    url: '/api/v1/repositories/{owner}/{repo}/issues/{number}/comments';
};

export type commentsCreateCommentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type commentsCreateCommentError = commentsCreateCommentErrors[keyof commentsCreateCommentErrors];

export type commentsCreateCommentResponses = {
    /**
     * Successful Response
     */
    201: CommentPublic;
};

export type commentsCreateCommentResponse = commentsCreateCommentResponses[keyof commentsCreateCommentResponses];

export type commentsDeleteCommentData = {
    body?: never;
    path: {
        /**
         * Comment Id
         */
        comment_id: string;
    };
    query?: never;
    url: '/api/v1/comments/{comment_id}';
};

export type commentsDeleteCommentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type commentsDeleteCommentError = commentsDeleteCommentErrors[keyof commentsDeleteCommentErrors];

export type commentsDeleteCommentResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type commentsDeleteCommentResponse = commentsDeleteCommentResponses[keyof commentsDeleteCommentResponses];

export type commentsUpdateCommentData = {
    body: CommentUpdate;
    path: {
        /**
         * Comment Id
         */
        comment_id: string;
    };
    query?: never;
    url: '/api/v1/comments/{comment_id}';
};

export type commentsUpdateCommentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type commentsUpdateCommentError = commentsUpdateCommentErrors[keyof commentsUpdateCommentErrors];

export type commentsUpdateCommentResponses = {
    /**
     * Successful Response
     */
    200: CommentPublic;
};

export type commentsUpdateCommentResponse = commentsUpdateCommentResponses[keyof commentsUpdateCommentResponses];

export type releasesListReleasesData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
    };
    query?: {
        /**
         * Include Drafts
         */
        include_drafts?: boolean;
    };
    url: '/api/v1/repositories/{owner}/{repo}/releases';
};

export type releasesListReleasesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type releasesListReleasesError = releasesListReleasesErrors[keyof releasesListReleasesErrors];

export type releasesListReleasesResponses = {
    /**
     * Successful Response
     */
    200: ReleasesPublic;
};

export type releasesListReleasesResponse = releasesListReleasesResponses[keyof releasesListReleasesResponses];

export type releasesCreateReleaseData = {
    body: ReleaseCreate;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
    };
    query?: never;
    url: '/api/v1/repositories/{owner}/{repo}/releases';
};

export type releasesCreateReleaseErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type releasesCreateReleaseError = releasesCreateReleaseErrors[keyof releasesCreateReleaseErrors];

export type releasesCreateReleaseResponses = {
    /**
     * Successful Response
     */
    201: ReleasePublic;
};

export type releasesCreateReleaseResponse = releasesCreateReleaseResponses[keyof releasesCreateReleaseResponses];

export type releasesGetReleaseData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
        /**
         * Tag Name
         */
        tag_name: string;
    };
    query?: never;
    url: '/api/v1/repositories/{owner}/{repo}/releases/{tag_name}';
};

export type releasesGetReleaseErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type releasesGetReleaseError = releasesGetReleaseErrors[keyof releasesGetReleaseErrors];

export type releasesGetReleaseResponses = {
    /**
     * Successful Response
     */
    200: ReleasePublic;
};

export type releasesGetReleaseResponse = releasesGetReleaseResponses[keyof releasesGetReleaseResponses];

export type releasesUpdateReleaseData = {
    body: ReleaseUpdate;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
        /**
         * Tag Name
         */
        tag_name: string;
    };
    query?: never;
    url: '/api/v1/repositories/{owner}/{repo}/releases/{tag_name}';
};

export type releasesUpdateReleaseErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type releasesUpdateReleaseError = releasesUpdateReleaseErrors[keyof releasesUpdateReleaseErrors];

export type releasesUpdateReleaseResponses = {
    /**
     * Successful Response
     */
    200: ReleasePublic;
};

export type releasesUpdateReleaseResponse = releasesUpdateReleaseResponses[keyof releasesUpdateReleaseResponses];

export type releasesListTagsData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
    };
    query?: never;
    url: '/api/v1/repositories/{owner}/{repo}/tags';
};

export type releasesListTagsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type releasesListTagsError = releasesListTagsErrors[keyof releasesListTagsErrors];

export type releasesListTagsResponses = {
    /**
     * Successful Response
     */
    200: TagsPublic;
};

export type releasesListTagsResponse = releasesListTagsResponses[keyof releasesListTagsResponses];

export type activityGetRepositoryActivityData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
    };
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/repositories/{owner}/{repo}/activity';
};

export type activityGetRepositoryActivityErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type activityGetRepositoryActivityError = activityGetRepositoryActivityErrors[keyof activityGetRepositoryActivityErrors];

export type activityGetRepositoryActivityResponses = {
    /**
     * Successful Response
     */
    200: ActivitiesPublic;
};

export type activityGetRepositoryActivityResponse = activityGetRepositoryActivityResponses[keyof activityGetRepositoryActivityResponses];

export type activityGetFeedData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/me/feed';
};

export type activityGetFeedErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type activityGetFeedError = activityGetFeedErrors[keyof activityGetFeedErrors];

export type activityGetFeedResponses = {
    /**
     * Successful Response
     */
    200: ActivitiesPublic;
};

export type activityGetFeedResponse = activityGetFeedResponses[keyof activityGetFeedResponses];

export type profilesReadUserByUsernameData = {
    body?: never;
    path: {
        /**
         * Username
         */
        username: string;
    };
    query?: never;
    url: '/api/v1/users/{username}';
};

export type profilesReadUserByUsernameErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type profilesReadUserByUsernameError = profilesReadUserByUsernameErrors[keyof profilesReadUserByUsernameErrors];

export type profilesReadUserByUsernameResponses = {
    /**
     * Successful Response
     */
    200: ProfilePublic;
};

export type profilesReadUserByUsernameResponse = profilesReadUserByUsernameResponses[keyof profilesReadUserByUsernameResponses];

export type profilesListUserRepositoriesData = {
    body?: never;
    path: {
        /**
         * Username
         */
        username: string;
    };
    query?: never;
    url: '/api/v1/users/{username}/repositories';
};

export type profilesListUserRepositoriesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type profilesListUserRepositoriesError = profilesListUserRepositoriesErrors[keyof profilesListUserRepositoriesErrors];

export type profilesListUserRepositoriesResponses = {
    /**
     * Successful Response
     */
    200: RepositoriesPublic;
};

export type profilesListUserRepositoriesResponse = profilesListUserRepositoriesResponses[keyof profilesListUserRepositoriesResponses];

export type profilesListUserStarredRepositoriesData = {
    body?: never;
    path: {
        /**
         * Username
         */
        username: string;
    };
    query?: never;
    url: '/api/v1/users/{username}/starred';
};

export type profilesListUserStarredRepositoriesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type profilesListUserStarredRepositoriesError = profilesListUserStarredRepositoriesErrors[keyof profilesListUserStarredRepositoriesErrors];

export type profilesListUserStarredRepositoriesResponses = {
    /**
     * Successful Response
     */
    200: RepositoriesPublic;
};

export type profilesListUserStarredRepositoriesResponse = profilesListUserStarredRepositoriesResponses[keyof profilesListUserStarredRepositoriesResponses];

export type repositoriesListRepositoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/repositories/';
};

export type repositoriesListRepositoriesResponses = {
    /**
     * Successful Response
     */
    200: RepositoriesPublic;
};

export type repositoriesListRepositoriesResponse = repositoriesListRepositoriesResponses[keyof repositoriesListRepositoriesResponses];

export type repositoriesCreateRepositoryData = {
    body: CreateRepositoryRequest;
    path?: never;
    query?: never;
    url: '/api/v1/repositories/';
};

export type repositoriesCreateRepositoryErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesCreateRepositoryError = repositoriesCreateRepositoryErrors[keyof repositoriesCreateRepositoryErrors];

export type repositoriesCreateRepositoryResponses = {
    /**
     * Successful Response
     */
    201: Repository;
};

export type repositoriesCreateRepositoryResponse = repositoriesCreateRepositoryResponses[keyof repositoriesCreateRepositoryResponses];

export type repositoriesGetTreeData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
    };
    query?: {
        /**
         * Ref
         */
        ref?: string;
        /**
         * Tree Path
         */
        tree_path?: string;
    };
    url: '/api/v1/repositories/{owner}/{repo}/tree';
};

export type repositoriesGetTreeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesGetTreeError = repositoriesGetTreeErrors[keyof repositoriesGetTreeErrors];

export type repositoriesGetTreeResponses = {
    /**
     * Successful Response
     */
    200: TreeListing;
};

export type repositoriesGetTreeResponse = repositoriesGetTreeResponses[keyof repositoriesGetTreeResponses];

export type repositoriesGetBlobData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
    };
    query?: {
        /**
         * Ref
         */
        ref?: string;
        /**
         * File Path
         */
        file_path?: string;
    };
    url: '/api/v1/repositories/{owner}/{repo}/blob';
};

export type repositoriesGetBlobErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesGetBlobError = repositoriesGetBlobErrors[keyof repositoriesGetBlobErrors];

export type repositoriesGetBlobResponses = {
    /**
     * Successful Response
     */
    200: FileContent;
};

export type repositoriesGetBlobResponse = repositoriesGetBlobResponses[keyof repositoriesGetBlobResponses];

export type repositoriesGetRepositoryInfoData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
    };
    query?: {
        /**
         * Ref
         */
        ref?: string;
    };
    url: '/api/v1/repositories/{owner}/{repo}/info';
};

export type repositoriesGetRepositoryInfoErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesGetRepositoryInfoError = repositoriesGetRepositoryInfoErrors[keyof repositoriesGetRepositoryInfoErrors];

export type repositoriesGetRepositoryInfoResponses = {
    /**
     * Successful Response
     */
    200: RepositoryInfo;
};

export type repositoriesGetRepositoryInfoResponse = repositoriesGetRepositoryInfoResponses[keyof repositoriesGetRepositoryInfoResponses];

export type repositoriesGetReadmeData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
    };
    query?: {
        /**
         * Ref
         */
        ref?: string;
        /**
         * Tree Path
         */
        tree_path?: string;
    };
    url: '/api/v1/repositories/{owner}/{repo}/readme';
};

export type repositoriesGetReadmeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesGetReadmeError = repositoriesGetReadmeErrors[keyof repositoriesGetReadmeErrors];

export type repositoriesGetReadmeResponses = {
    /**
     * Successful Response
     */
    200: ReadmeContent;
};

export type repositoriesGetReadmeResponse = repositoriesGetReadmeResponses[keyof repositoriesGetReadmeResponses];

export type repositoriesListBranchesData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
    };
    query?: never;
    url: '/api/v1/repositories/{owner}/{repo}/branches';
};

export type repositoriesListBranchesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesListBranchesError = repositoriesListBranchesErrors[keyof repositoriesListBranchesErrors];

export type repositoriesListBranchesResponses = {
    /**
     * Response Repositories-List Branches
     *
     * Successful Response
     */
    200: Array<BranchInfo>;
};

export type repositoriesListBranchesResponse = repositoriesListBranchesResponses[keyof repositoriesListBranchesResponses];

export type repositoriesListCommitsData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
    };
    query?: {
        /**
         * Ref
         */
        ref?: string;
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/repositories/{owner}/{repo}/commits';
};

export type repositoriesListCommitsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesListCommitsError = repositoriesListCommitsErrors[keyof repositoriesListCommitsErrors];

export type repositoriesListCommitsResponses = {
    /**
     * Successful Response
     */
    200: CommitsPublic;
};

export type repositoriesListCommitsResponse = repositoriesListCommitsResponses[keyof repositoriesListCommitsResponses];

export type repositoriesGetCommitData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
        /**
         * Sha
         */
        sha: string;
    };
    query?: never;
    url: '/api/v1/repositories/{owner}/{repo}/commits/{sha}';
};

export type repositoriesGetCommitErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesGetCommitError = repositoriesGetCommitErrors[keyof repositoriesGetCommitErrors];

export type repositoriesGetCommitResponses = {
    /**
     * Successful Response
     */
    200: CommitDetail;
};

export type repositoriesGetCommitResponse = repositoriesGetCommitResponses[keyof repositoriesGetCommitResponses];

export type repositoriesListIssuesData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
    };
    query?: {
        /**
         * State
         *
         * Filter by state: open, closed, or all
         */
        state?: string;
    };
    url: '/api/v1/repositories/{owner}/{repo}/issues';
};

export type repositoriesListIssuesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesListIssuesError = repositoriesListIssuesErrors[keyof repositoriesListIssuesErrors];

export type repositoriesListIssuesResponses = {
    /**
     * Successful Response
     */
    200: IssuesListPublic;
};

export type repositoriesListIssuesResponse = repositoriesListIssuesResponses[keyof repositoriesListIssuesResponses];

export type repositoriesCreateIssueData = {
    body: IssueCreate;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
    };
    query?: never;
    url: '/api/v1/repositories/{owner}/{repo}/issues';
};

export type repositoriesCreateIssueErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesCreateIssueError = repositoriesCreateIssueErrors[keyof repositoriesCreateIssueErrors];

export type repositoriesCreateIssueResponses = {
    /**
     * Successful Response
     */
    201: IssuePublic;
};

export type repositoriesCreateIssueResponse = repositoriesCreateIssueResponses[keyof repositoriesCreateIssueResponses];

export type repositoriesGetIssueData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
        /**
         * Number
         */
        number: number;
    };
    query?: never;
    url: '/api/v1/repositories/{owner}/{repo}/issues/{number}';
};

export type repositoriesGetIssueErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesGetIssueError = repositoriesGetIssueErrors[keyof repositoriesGetIssueErrors];

export type repositoriesGetIssueResponses = {
    /**
     * Successful Response
     */
    200: IssuePublic;
};

export type repositoriesGetIssueResponse = repositoriesGetIssueResponses[keyof repositoriesGetIssueResponses];

export type repositoriesUpdateIssueData = {
    body: IssueUpdate;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
        /**
         * Number
         */
        number: number;
    };
    query?: never;
    url: '/api/v1/repositories/{owner}/{repo}/issues/{number}';
};

export type repositoriesUpdateIssueErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesUpdateIssueError = repositoriesUpdateIssueErrors[keyof repositoriesUpdateIssueErrors];

export type repositoriesUpdateIssueResponses = {
    /**
     * Successful Response
     */
    200: IssuePublic;
};

export type repositoriesUpdateIssueResponse = repositoriesUpdateIssueResponses[keyof repositoriesUpdateIssueResponses];

export type repositoriesListPullRequestsData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
    };
    query?: {
        /**
         * State
         *
         * Filter by state: open, closed, merged, or all
         */
        state?: string;
    };
    url: '/api/v1/repositories/{owner}/{repo}/pulls';
};

export type repositoriesListPullRequestsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesListPullRequestsError = repositoriesListPullRequestsErrors[keyof repositoriesListPullRequestsErrors];

export type repositoriesListPullRequestsResponses = {
    /**
     * Successful Response
     */
    200: PullRequestsListPublic;
};

export type repositoriesListPullRequestsResponse = repositoriesListPullRequestsResponses[keyof repositoriesListPullRequestsResponses];

export type repositoriesCreatePullRequestData = {
    body: PullRequestCreate;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
    };
    query?: never;
    url: '/api/v1/repositories/{owner}/{repo}/pulls';
};

export type repositoriesCreatePullRequestErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesCreatePullRequestError = repositoriesCreatePullRequestErrors[keyof repositoriesCreatePullRequestErrors];

export type repositoriesCreatePullRequestResponses = {
    /**
     * Successful Response
     */
    201: PullRequestPublic;
};

export type repositoriesCreatePullRequestResponse = repositoriesCreatePullRequestResponses[keyof repositoriesCreatePullRequestResponses];

export type repositoriesGetPullRequestData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
        /**
         * Number
         */
        number: number;
    };
    query?: never;
    url: '/api/v1/repositories/{owner}/{repo}/pulls/{number}';
};

export type repositoriesGetPullRequestErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesGetPullRequestError = repositoriesGetPullRequestErrors[keyof repositoriesGetPullRequestErrors];

export type repositoriesGetPullRequestResponses = {
    /**
     * Successful Response
     */
    200: PullRequestPublic;
};

export type repositoriesGetPullRequestResponse = repositoriesGetPullRequestResponses[keyof repositoriesGetPullRequestResponses];

export type repositoriesUpdatePullRequestData = {
    body: PullRequestUpdate;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
        /**
         * Number
         */
        number: number;
    };
    query?: never;
    url: '/api/v1/repositories/{owner}/{repo}/pulls/{number}';
};

export type repositoriesUpdatePullRequestErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesUpdatePullRequestError = repositoriesUpdatePullRequestErrors[keyof repositoriesUpdatePullRequestErrors];

export type repositoriesUpdatePullRequestResponses = {
    /**
     * Successful Response
     */
    200: PullRequestPublic;
};

export type repositoriesUpdatePullRequestResponse = repositoriesUpdatePullRequestResponses[keyof repositoriesUpdatePullRequestResponses];

export type repositoriesGetPullRequestFilesData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
        /**
         * Number
         */
        number: number;
    };
    query?: never;
    url: '/api/v1/repositories/{owner}/{repo}/pulls/{number}/files';
};

export type repositoriesGetPullRequestFilesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesGetPullRequestFilesError = repositoriesGetPullRequestFilesErrors[keyof repositoriesGetPullRequestFilesErrors];

export type repositoriesGetPullRequestFilesResponses = {
    /**
     * Successful Response
     */
    200: CompareResult;
};

export type repositoriesGetPullRequestFilesResponse = repositoriesGetPullRequestFilesResponses[keyof repositoriesGetPullRequestFilesResponses];

export type repositoriesGetRepositoryData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
    };
    query?: never;
    url: '/api/v1/repositories/{owner}/{repo}';
};

export type repositoriesGetRepositoryErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesGetRepositoryError = repositoriesGetRepositoryErrors[keyof repositoriesGetRepositoryErrors];

export type repositoriesGetRepositoryResponses = {
    /**
     * Successful Response
     */
    200: Repository;
};

export type repositoriesGetRepositoryResponse = repositoriesGetRepositoryResponses[keyof repositoriesGetRepositoryResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];
