// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * BranchInfo
 *
 * Information about a branch.
 */
export type BranchInfo = {
    /**
     * Name
     */
    name: string;
    /**
     * Is Default
     */
    is_default: boolean;
};

/**
 * CommitInfo
 *
 * Information about a commit.
 */
export type CommitInfo = {
    /**
     * Sha
     */
    sha: string;
    /**
     * Message
     */
    message: string;
    /**
     * Author
     */
    author: string;
    /**
     * Timestamp
     */
    timestamp: number;
};

/**
 * CreateRepositoryRequest
 *
 * Request to create a new repository.
 */
export type CreateRepositoryRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Owner
     */
    owner: string;
};

/**
 * FileContent
 *
 * File content with syntax highlighting.
 */
export type FileContent = {
    /**
     * Name
     */
    name: string;
    /**
     * Path
     */
    path: string;
    /**
     * Size
     */
    size: number;
    /**
     * Content
     */
    content: string;
    /**
     * Highlighted Html
     */
    highlighted_html: string;
    /**
     * Css
     */
    css: string;
    /**
     * Css Dark
     */
    css_dark: string;
    /**
     * Language
     */
    language: string;
    /**
     * Line Count
     */
    line_count: number;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IssueCreate
 *
 * Request to create a new issue.
 */
export type IssueCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Body
     */
    body?: string | null;
};

/**
 * IssuePublic
 *
 * Public issue representation.
 */
export type IssuePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Repo Path
     */
    repo_path: string;
    /**
     * Number
     */
    number: number;
    /**
     * Title
     */
    title: string;
    /**
     * Body
     */
    body?: string | null;
    /**
     * State
     */
    state: string;
    /**
     * Author Email
     */
    author_email?: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * IssueUpdate
 *
 * Request to update an issue.
 */
export type IssueUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Body
     */
    body?: string | null;
    /**
     * State
     */
    state?: string | null;
};

/**
 * IssuesListPublic
 *
 * List of issues.
 */
export type IssuesListPublic = {
    /**
     * Data
     */
    data: Array<IssuePublic>;
    /**
     * Count
     */
    count: number;
    /**
     * Open Count
     */
    open_count: number;
    /**
     * Closed Count
     */
    closed_count: number;
};

/**
 * NewPassword
 *
 * Schema for password reset with token.
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PrivateUserCreate
 *
 * Schema for creating a user via private API.
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * PullRequestCreate
 *
 * Request to create a new pull request.
 */
export type PullRequestCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Body
     */
    body?: string | null;
    /**
     * Head Branch
     */
    head_branch: string;
    /**
     * Base Branch
     */
    base_branch?: string;
};

/**
 * PullRequestPublic
 *
 * Public pull request representation.
 */
export type PullRequestPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Repo Path
     */
    repo_path: string;
    /**
     * Number
     */
    number: number;
    /**
     * Title
     */
    title: string;
    /**
     * Body
     */
    body?: string | null;
    /**
     * State
     */
    state: string;
    /**
     * Head Branch
     */
    head_branch: string;
    /**
     * Base Branch
     */
    base_branch: string;
    /**
     * Author Email
     */
    author_email?: string | null;
    /**
     * Merge Base
     */
    merge_base?: string | null;
    /**
     * Merged Commit Id
     */
    merged_commit_id?: string | null;
    /**
     * Has Merged
     */
    has_merged?: boolean;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * PullRequestUpdate
 *
 * Request to update a pull request.
 */
export type PullRequestUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Body
     */
    body?: string | null;
    /**
     * State
     */
    state?: string | null;
};

/**
 * PullRequestsListPublic
 *
 * List of pull requests.
 */
export type PullRequestsListPublic = {
    /**
     * Data
     */
    data: Array<PullRequestPublic>;
    /**
     * Count
     */
    count: number;
    /**
     * Open Count
     */
    open_count: number;
    /**
     * Closed Count
     */
    closed_count: number;
};

/**
 * ReadmeContent
 *
 * README file content.
 */
export type ReadmeContent = {
    /**
     * Filename
     */
    filename: string;
    /**
     * Content
     */
    content: string;
    /**
     * Html
     */
    html: string;
};

/**
 * RepositoriesPublic
 *
 * List of repositories.
 */
export type RepositoriesPublic = {
    /**
     * Data
     */
    data: Array<Repository>;
    /**
     * Count
     */
    count: number;
};

/**
 * Repository
 *
 * Repository schema.
 */
export type Repository = {
    /**
     * Name
     */
    name: string;
    /**
     * Path
     */
    path: string;
};

/**
 * RepositoryInfo
 *
 * Extended repository information with metadata.
 */
export type RepositoryInfo = {
    /**
     * Name
     */
    name: string;
    /**
     * Path
     */
    path: string;
    /**
     * Default Branch
     */
    default_branch: string;
    /**
     * Branch Count
     */
    branch_count: number;
    /**
     * Tag Count
     */
    tag_count: number;
    last_commit?: CommitInfo | null;
};

/**
 * Token
 *
 * OAuth2 token response schema.
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * TreeEntry
 *
 * A single entry in a Git tree (file or directory).
 */
export type TreeEntry = {
    /**
     * Name
     */
    name: string;
    /**
     * Path
     */
    path: string;
    /**
     * Type
     */
    type: string;
    /**
     * Size
     */
    size?: number | null;
};

/**
 * TreeListing
 *
 * Directory listing for a repository path.
 */
export type TreeListing = {
    /**
     * Entries
     */
    entries: Array<TreeEntry>;
    /**
     * Repo Path
     */
    repo_path: string;
    /**
     * Tree Path
     */
    tree_path: string;
    /**
     * Ref
     */
    ref: string;
};

/**
 * UpdatePassword
 *
 * Schema for password update.
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 *
 * Schema for creating a new user.
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 *
 * Schema for returning user data to clients.
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
};

/**
 * UserRegister
 *
 * Schema for user self-registration.
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 *
 * Schema for updating a user (admin).
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 *
 * Schema for users updating their own profile.
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 *
 * Schema for paginated list of users.
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type gitGetInfoRefsData = {
    body?: never;
    path: {
        /**
         * Repo Path
         */
        repo_path: string;
    };
    query?: never;
    url: '/api/v1/{repo_path}/info/refs';
};

export type gitGetInfoRefsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type gitGetInfoRefsError = gitGetInfoRefsErrors[keyof gitGetInfoRefsErrors];

export type gitGetInfoRefsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type gitGetHeadData = {
    body?: never;
    path: {
        /**
         * Repo Path
         */
        repo_path: string;
    };
    query?: never;
    url: '/api/v1/{repo_path}/HEAD';
};

export type gitGetHeadErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type gitGetHeadError = gitGetHeadErrors[keyof gitGetHeadErrors];

export type gitGetHeadResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type gitGetInfoPacksData = {
    body?: never;
    path: {
        /**
         * Repo Path
         */
        repo_path: string;
    };
    query?: never;
    url: '/api/v1/{repo_path}/objects/info/packs';
};

export type gitGetInfoPacksErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type gitGetInfoPacksError = gitGetInfoPacksErrors[keyof gitGetInfoPacksErrors];

export type gitGetInfoPacksResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type gitGetLooseObjectData = {
    body?: never;
    path: {
        /**
         * Repo Path
         */
        repo_path: string;
        /**
         * Prefix
         */
        prefix: string;
        /**
         * Suffix
         */
        suffix: string;
    };
    query?: never;
    url: '/api/v1/{repo_path}/objects/{prefix}/{suffix}';
};

export type gitGetLooseObjectErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type gitGetLooseObjectError = gitGetLooseObjectErrors[keyof gitGetLooseObjectErrors];

export type gitGetLooseObjectResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type gitGetPackFileData = {
    body?: never;
    path: {
        /**
         * Repo Path
         */
        repo_path: string;
        /**
         * Pack File
         */
        pack_file: string;
    };
    query?: never;
    url: '/api/v1/{repo_path}/objects/pack/{pack_file}';
};

export type gitGetPackFileErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type gitGetPackFileError = gitGetPackFileErrors[keyof gitGetPackFileErrors];

export type gitGetPackFileResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type gitGitUploadPackData = {
    body?: never;
    path: {
        /**
         * Repo Path
         */
        repo_path: string;
    };
    query?: never;
    url: '/api/v1/{repo_path}/git-upload-pack';
};

export type gitGitUploadPackErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type gitGitUploadPackError = gitGitUploadPackErrors[keyof gitGitUploadPackErrors];

export type gitGitUploadPackResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type gitGitReceivePackData = {
    body?: never;
    path: {
        /**
         * Repo Path
         */
        repo_path: string;
    };
    query?: never;
    url: '/api/v1/{repo_path}/git-receive-pack';
};

export type gitGitReceivePackErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type gitGitReceivePackError = gitGitReceivePackErrors[keyof gitGitReceivePackErrors];

export type gitGitReceivePackResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type repositoriesListRepositoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/repositories/';
};

export type repositoriesListRepositoriesResponses = {
    /**
     * Successful Response
     */
    200: RepositoriesPublic;
};

export type repositoriesListRepositoriesResponse = repositoriesListRepositoriesResponses[keyof repositoriesListRepositoriesResponses];

export type repositoriesCreateRepositoryData = {
    body: CreateRepositoryRequest;
    path?: never;
    query?: never;
    url: '/api/v1/repositories/';
};

export type repositoriesCreateRepositoryErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesCreateRepositoryError = repositoriesCreateRepositoryErrors[keyof repositoriesCreateRepositoryErrors];

export type repositoriesCreateRepositoryResponses = {
    /**
     * Successful Response
     */
    201: Repository;
};

export type repositoriesCreateRepositoryResponse = repositoriesCreateRepositoryResponses[keyof repositoriesCreateRepositoryResponses];

export type repositoriesGetTreeData = {
    body?: never;
    path: {
        /**
         * Path
         */
        path: string;
    };
    query?: {
        /**
         * Ref
         */
        ref?: string;
        /**
         * Tree Path
         */
        tree_path?: string;
    };
    url: '/api/v1/repositories/{path}/tree';
};

export type repositoriesGetTreeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesGetTreeError = repositoriesGetTreeErrors[keyof repositoriesGetTreeErrors];

export type repositoriesGetTreeResponses = {
    /**
     * Successful Response
     */
    200: TreeListing;
};

export type repositoriesGetTreeResponse = repositoriesGetTreeResponses[keyof repositoriesGetTreeResponses];

export type repositoriesGetBlobData = {
    body?: never;
    path: {
        /**
         * Path
         */
        path: string;
    };
    query?: {
        /**
         * Ref
         */
        ref?: string;
        /**
         * File Path
         */
        file_path?: string;
    };
    url: '/api/v1/repositories/{path}/blob';
};

export type repositoriesGetBlobErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesGetBlobError = repositoriesGetBlobErrors[keyof repositoriesGetBlobErrors];

export type repositoriesGetBlobResponses = {
    /**
     * Successful Response
     */
    200: FileContent;
};

export type repositoriesGetBlobResponse = repositoriesGetBlobResponses[keyof repositoriesGetBlobResponses];

export type repositoriesGetRepositoryInfoData = {
    body?: never;
    path: {
        /**
         * Path
         */
        path: string;
    };
    query?: {
        /**
         * Ref
         */
        ref?: string;
    };
    url: '/api/v1/repositories/{path}/info';
};

export type repositoriesGetRepositoryInfoErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesGetRepositoryInfoError = repositoriesGetRepositoryInfoErrors[keyof repositoriesGetRepositoryInfoErrors];

export type repositoriesGetRepositoryInfoResponses = {
    /**
     * Successful Response
     */
    200: RepositoryInfo;
};

export type repositoriesGetRepositoryInfoResponse = repositoriesGetRepositoryInfoResponses[keyof repositoriesGetRepositoryInfoResponses];

export type repositoriesGetReadmeData = {
    body?: never;
    path: {
        /**
         * Path
         */
        path: string;
    };
    query?: {
        /**
         * Ref
         */
        ref?: string;
        /**
         * Tree Path
         */
        tree_path?: string;
    };
    url: '/api/v1/repositories/{path}/readme';
};

export type repositoriesGetReadmeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesGetReadmeError = repositoriesGetReadmeErrors[keyof repositoriesGetReadmeErrors];

export type repositoriesGetReadmeResponses = {
    /**
     * Successful Response
     */
    200: ReadmeContent;
};

export type repositoriesGetReadmeResponse = repositoriesGetReadmeResponses[keyof repositoriesGetReadmeResponses];

export type repositoriesListBranchesData = {
    body?: never;
    path: {
        /**
         * Path
         */
        path: string;
    };
    query?: never;
    url: '/api/v1/repositories/{path}/branches';
};

export type repositoriesListBranchesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesListBranchesError = repositoriesListBranchesErrors[keyof repositoriesListBranchesErrors];

export type repositoriesListBranchesResponses = {
    /**
     * Response Repositories-List Branches
     *
     * Successful Response
     */
    200: Array<BranchInfo>;
};

export type repositoriesListBranchesResponse = repositoriesListBranchesResponses[keyof repositoriesListBranchesResponses];

export type repositoriesListIssuesData = {
    body?: never;
    path: {
        /**
         * Path
         */
        path: string;
    };
    query?: {
        /**
         * State
         *
         * Filter by state: open, closed, or all
         */
        state?: string;
    };
    url: '/api/v1/repositories/{path}/issues';
};

export type repositoriesListIssuesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesListIssuesError = repositoriesListIssuesErrors[keyof repositoriesListIssuesErrors];

export type repositoriesListIssuesResponses = {
    /**
     * Successful Response
     */
    200: IssuesListPublic;
};

export type repositoriesListIssuesResponse = repositoriesListIssuesResponses[keyof repositoriesListIssuesResponses];

export type repositoriesCreateIssueData = {
    body: IssueCreate;
    path: {
        /**
         * Path
         */
        path: string;
    };
    query?: never;
    url: '/api/v1/repositories/{path}/issues';
};

export type repositoriesCreateIssueErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesCreateIssueError = repositoriesCreateIssueErrors[keyof repositoriesCreateIssueErrors];

export type repositoriesCreateIssueResponses = {
    /**
     * Successful Response
     */
    201: IssuePublic;
};

export type repositoriesCreateIssueResponse = repositoriesCreateIssueResponses[keyof repositoriesCreateIssueResponses];

export type repositoriesGetIssueData = {
    body?: never;
    path: {
        /**
         * Path
         */
        path: string;
        /**
         * Number
         */
        number: number;
    };
    query?: never;
    url: '/api/v1/repositories/{path}/issues/{number}';
};

export type repositoriesGetIssueErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesGetIssueError = repositoriesGetIssueErrors[keyof repositoriesGetIssueErrors];

export type repositoriesGetIssueResponses = {
    /**
     * Successful Response
     */
    200: IssuePublic;
};

export type repositoriesGetIssueResponse = repositoriesGetIssueResponses[keyof repositoriesGetIssueResponses];

export type repositoriesUpdateIssueData = {
    body: IssueUpdate;
    path: {
        /**
         * Path
         */
        path: string;
        /**
         * Number
         */
        number: number;
    };
    query?: never;
    url: '/api/v1/repositories/{path}/issues/{number}';
};

export type repositoriesUpdateIssueErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesUpdateIssueError = repositoriesUpdateIssueErrors[keyof repositoriesUpdateIssueErrors];

export type repositoriesUpdateIssueResponses = {
    /**
     * Successful Response
     */
    200: IssuePublic;
};

export type repositoriesUpdateIssueResponse = repositoriesUpdateIssueResponses[keyof repositoriesUpdateIssueResponses];

export type repositoriesListPullRequestsData = {
    body?: never;
    path: {
        /**
         * Path
         */
        path: string;
    };
    query?: {
        /**
         * State
         *
         * Filter by state: open, closed, merged, or all
         */
        state?: string;
    };
    url: '/api/v1/repositories/{path}/pulls';
};

export type repositoriesListPullRequestsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesListPullRequestsError = repositoriesListPullRequestsErrors[keyof repositoriesListPullRequestsErrors];

export type repositoriesListPullRequestsResponses = {
    /**
     * Successful Response
     */
    200: PullRequestsListPublic;
};

export type repositoriesListPullRequestsResponse = repositoriesListPullRequestsResponses[keyof repositoriesListPullRequestsResponses];

export type repositoriesCreatePullRequestData = {
    body: PullRequestCreate;
    path: {
        /**
         * Path
         */
        path: string;
    };
    query?: never;
    url: '/api/v1/repositories/{path}/pulls';
};

export type repositoriesCreatePullRequestErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesCreatePullRequestError = repositoriesCreatePullRequestErrors[keyof repositoriesCreatePullRequestErrors];

export type repositoriesCreatePullRequestResponses = {
    /**
     * Successful Response
     */
    201: PullRequestPublic;
};

export type repositoriesCreatePullRequestResponse = repositoriesCreatePullRequestResponses[keyof repositoriesCreatePullRequestResponses];

export type repositoriesGetPullRequestData = {
    body?: never;
    path: {
        /**
         * Path
         */
        path: string;
        /**
         * Number
         */
        number: number;
    };
    query?: never;
    url: '/api/v1/repositories/{path}/pulls/{number}';
};

export type repositoriesGetPullRequestErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesGetPullRequestError = repositoriesGetPullRequestErrors[keyof repositoriesGetPullRequestErrors];

export type repositoriesGetPullRequestResponses = {
    /**
     * Successful Response
     */
    200: PullRequestPublic;
};

export type repositoriesGetPullRequestResponse = repositoriesGetPullRequestResponses[keyof repositoriesGetPullRequestResponses];

export type repositoriesUpdatePullRequestData = {
    body: PullRequestUpdate;
    path: {
        /**
         * Path
         */
        path: string;
        /**
         * Number
         */
        number: number;
    };
    query?: never;
    url: '/api/v1/repositories/{path}/pulls/{number}';
};

export type repositoriesUpdatePullRequestErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesUpdatePullRequestError = repositoriesUpdatePullRequestErrors[keyof repositoriesUpdatePullRequestErrors];

export type repositoriesUpdatePullRequestResponses = {
    /**
     * Successful Response
     */
    200: PullRequestPublic;
};

export type repositoriesUpdatePullRequestResponse = repositoriesUpdatePullRequestResponses[keyof repositoriesUpdatePullRequestResponses];

export type repositoriesGetRepositoryData = {
    body?: never;
    path: {
        /**
         * Path
         */
        path: string;
    };
    query?: never;
    url: '/api/v1/repositories/{path}';
};

export type repositoriesGetRepositoryErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesGetRepositoryError = repositoriesGetRepositoryErrors[keyof repositoriesGetRepositoryErrors];

export type repositoriesGetRepositoryResponses = {
    /**
     * Successful Response
     */
    200: Repository;
};

export type repositoriesGetRepositoryResponse = repositoriesGetRepositoryResponses[keyof repositoriesGetRepositoryResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];
