// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * CreateRepositoryRequest
 *
 * Request to create a new repository.
 */
export type CreateRepositoryRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Owner
     */
    owner: string;
};

/**
 * FileContent
 *
 * File content with syntax highlighting.
 */
export type FileContent = {
    /**
     * Name
     */
    name: string;
    /**
     * Path
     */
    path: string;
    /**
     * Size
     */
    size: number;
    /**
     * Content
     */
    content: string;
    /**
     * Highlighted Html
     */
    highlighted_html: string;
    /**
     * Css
     */
    css: string;
    /**
     * Css Dark
     */
    css_dark: string;
    /**
     * Language
     */
    language: string;
    /**
     * Line Count
     */
    line_count: number;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Message
 *
 * Generic message response schema.
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 *
 * Schema for password reset with token.
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PrivateUserCreate
 *
 * Schema for creating a user via private API.
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * RepositoriesPublic
 *
 * List of repositories.
 */
export type RepositoriesPublic = {
    /**
     * Data
     */
    data: Array<Repository>;
    /**
     * Count
     */
    count: number;
};

/**
 * Repository
 *
 * Repository schema.
 */
export type Repository = {
    /**
     * Name
     */
    name: string;
    /**
     * Path
     */
    path: string;
};

/**
 * Token
 *
 * OAuth2 token response schema.
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * TreeEntry
 *
 * A single entry in a Git tree (file or directory).
 */
export type TreeEntry = {
    /**
     * Name
     */
    name: string;
    /**
     * Path
     */
    path: string;
    /**
     * Type
     */
    type: string;
    /**
     * Size
     */
    size?: number | null;
};

/**
 * TreeListing
 *
 * Directory listing for a repository path.
 */
export type TreeListing = {
    /**
     * Entries
     */
    entries: Array<TreeEntry>;
    /**
     * Repo Path
     */
    repo_path: string;
    /**
     * Tree Path
     */
    tree_path: string;
    /**
     * Ref
     */
    ref: string;
};

/**
 * UpdatePassword
 *
 * Schema for password update.
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 *
 * Schema for creating a new user.
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 *
 * Schema for returning user data to clients.
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
};

/**
 * UserRegister
 *
 * Schema for user self-registration.
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 *
 * Schema for updating a user (admin).
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 *
 * Schema for users updating their own profile.
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 *
 * Schema for paginated list of users.
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type gitGetInfoRefsData = {
    body?: never;
    path: {
        /**
         * Repo Path
         */
        repo_path: string;
    };
    query?: never;
    url: '/api/v1/{repo_path}/info/refs';
};

export type gitGetInfoRefsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type gitGetInfoRefsError = gitGetInfoRefsErrors[keyof gitGetInfoRefsErrors];

export type gitGetInfoRefsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type gitGetHeadData = {
    body?: never;
    path: {
        /**
         * Repo Path
         */
        repo_path: string;
    };
    query?: never;
    url: '/api/v1/{repo_path}/HEAD';
};

export type gitGetHeadErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type gitGetHeadError = gitGetHeadErrors[keyof gitGetHeadErrors];

export type gitGetHeadResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type gitGetInfoPacksData = {
    body?: never;
    path: {
        /**
         * Repo Path
         */
        repo_path: string;
    };
    query?: never;
    url: '/api/v1/{repo_path}/objects/info/packs';
};

export type gitGetInfoPacksErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type gitGetInfoPacksError = gitGetInfoPacksErrors[keyof gitGetInfoPacksErrors];

export type gitGetInfoPacksResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type gitGetLooseObjectData = {
    body?: never;
    path: {
        /**
         * Repo Path
         */
        repo_path: string;
        /**
         * Prefix
         */
        prefix: string;
        /**
         * Suffix
         */
        suffix: string;
    };
    query?: never;
    url: '/api/v1/{repo_path}/objects/{prefix}/{suffix}';
};

export type gitGetLooseObjectErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type gitGetLooseObjectError = gitGetLooseObjectErrors[keyof gitGetLooseObjectErrors];

export type gitGetLooseObjectResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type gitGetPackFileData = {
    body?: never;
    path: {
        /**
         * Repo Path
         */
        repo_path: string;
        /**
         * Pack File
         */
        pack_file: string;
    };
    query?: never;
    url: '/api/v1/{repo_path}/objects/pack/{pack_file}';
};

export type gitGetPackFileErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type gitGetPackFileError = gitGetPackFileErrors[keyof gitGetPackFileErrors];

export type gitGetPackFileResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type gitGitUploadPackData = {
    body?: never;
    path: {
        /**
         * Repo Path
         */
        repo_path: string;
    };
    query?: never;
    url: '/api/v1/{repo_path}/git-upload-pack';
};

export type gitGitUploadPackErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type gitGitUploadPackError = gitGitUploadPackErrors[keyof gitGitUploadPackErrors];

export type gitGitUploadPackResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type gitGitReceivePackData = {
    body?: never;
    path: {
        /**
         * Repo Path
         */
        repo_path: string;
    };
    query?: never;
    url: '/api/v1/{repo_path}/git-receive-pack';
};

export type gitGitReceivePackErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type gitGitReceivePackError = gitGitReceivePackErrors[keyof gitGitReceivePackErrors];

export type gitGitReceivePackResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type repositoriesListRepositoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/repositories/';
};

export type repositoriesListRepositoriesResponses = {
    /**
     * Successful Response
     */
    200: RepositoriesPublic;
};

export type repositoriesListRepositoriesResponse = repositoriesListRepositoriesResponses[keyof repositoriesListRepositoriesResponses];

export type repositoriesCreateRepositoryData = {
    body: CreateRepositoryRequest;
    path?: never;
    query?: never;
    url: '/api/v1/repositories/';
};

export type repositoriesCreateRepositoryErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesCreateRepositoryError = repositoriesCreateRepositoryErrors[keyof repositoriesCreateRepositoryErrors];

export type repositoriesCreateRepositoryResponses = {
    /**
     * Successful Response
     */
    201: Repository;
};

export type repositoriesCreateRepositoryResponse = repositoriesCreateRepositoryResponses[keyof repositoriesCreateRepositoryResponses];

export type repositoriesGetTreeData = {
    body?: never;
    path: {
        /**
         * Path
         */
        path: string;
    };
    query?: {
        /**
         * Ref
         */
        ref?: string;
        /**
         * Tree Path
         */
        tree_path?: string;
    };
    url: '/api/v1/repositories/{path}/tree';
};

export type repositoriesGetTreeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesGetTreeError = repositoriesGetTreeErrors[keyof repositoriesGetTreeErrors];

export type repositoriesGetTreeResponses = {
    /**
     * Successful Response
     */
    200: TreeListing;
};

export type repositoriesGetTreeResponse = repositoriesGetTreeResponses[keyof repositoriesGetTreeResponses];

export type repositoriesGetBlobData = {
    body?: never;
    path: {
        /**
         * Path
         */
        path: string;
    };
    query?: {
        /**
         * Ref
         */
        ref?: string;
        /**
         * File Path
         */
        file_path?: string;
    };
    url: '/api/v1/repositories/{path}/blob';
};

export type repositoriesGetBlobErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesGetBlobError = repositoriesGetBlobErrors[keyof repositoriesGetBlobErrors];

export type repositoriesGetBlobResponses = {
    /**
     * Successful Response
     */
    200: FileContent;
};

export type repositoriesGetBlobResponse = repositoriesGetBlobResponses[keyof repositoriesGetBlobResponses];

export type repositoriesGetRepositoryData = {
    body?: never;
    path: {
        /**
         * Path
         */
        path: string;
    };
    query?: never;
    url: '/api/v1/repositories/{path}';
};

export type repositoriesGetRepositoryErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type repositoriesGetRepositoryError = repositoriesGetRepositoryErrors[keyof repositoriesGetRepositoryErrors];

export type repositoriesGetRepositoryResponses = {
    /**
     * Successful Response
     */
    200: Repository;
};

export type repositoriesGetRepositoryResponse = repositoriesGetRepositoryResponses[keyof repositoriesGetRepositoryResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];
