/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutRepositoriesRouteImport } from './routes/_layout/repositories'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutOwnerRepoIndexRouteImport } from './routes/_layout/$owner/$repo/index'
import { Route as LayoutOwnerRepoBlobRouteImport } from './routes/_layout/$owner/$repo/blob'
import { Route as LayoutOwnerRepoIssuesRouteImport } from './routes/_layout/$owner/$repo/issues'
import { Route as LayoutOwnerRepoPullsRouteImport } from './routes/_layout/$owner/$repo/pulls'
import { Route as LayoutOwnerRepoIssuesIndexRouteImport } from './routes/_layout/$owner/$repo/issues.index'
import { Route as LayoutOwnerRepoIssuesNewRouteImport } from './routes/_layout/$owner/$repo/issues.new'
import { Route as LayoutOwnerRepoPullsIndexRouteImport } from './routes/_layout/$owner/$repo/pulls.index'
import { Route as LayoutOwnerRepoPullsNewRouteImport } from './routes/_layout/$owner/$repo/pulls.new'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRepositoriesRoute = LayoutRepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnerRepoIndexRoute = LayoutOwnerRepoIndexRouteImport.update({
  id: '/$owner/$repo/',
  path: '/$owner/$repo/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnerRepoBlobRoute = LayoutOwnerRepoBlobRouteImport.update({
  id: '/$owner/$repo/blob',
  path: '/$owner/$repo/blob',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnerRepoIssuesRoute = LayoutOwnerRepoIssuesRouteImport.update({
  id: '/$owner/$repo/issues',
  path: '/$owner/$repo/issues',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnerRepoPullsRoute = LayoutOwnerRepoPullsRouteImport.update({
  id: '/$owner/$repo/pulls',
  path: '/$owner/$repo/pulls',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnerRepoIssuesIndexRoute =
  LayoutOwnerRepoIssuesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutOwnerRepoIssuesRoute,
  } as any)
const LayoutOwnerRepoIssuesNewRoute =
  LayoutOwnerRepoIssuesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => LayoutOwnerRepoIssuesRoute,
  } as any)
const LayoutOwnerRepoPullsIndexRoute =
  LayoutOwnerRepoPullsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutOwnerRepoPullsRoute,
  } as any)
const LayoutOwnerRepoPullsNewRoute = LayoutOwnerRepoPullsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LayoutOwnerRepoPullsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/repositories': typeof LayoutRepositoriesRoute
  '/settings': typeof LayoutSettingsRoute
  '/$owner/$repo/blob': typeof LayoutOwnerRepoBlobRoute
  '/$owner/$repo/issues': typeof LayoutOwnerRepoIssuesRouteWithChildren
  '/$owner/$repo/pulls': typeof LayoutOwnerRepoPullsRouteWithChildren
  '/$owner/$repo/': typeof LayoutOwnerRepoIndexRoute
  '/$owner/$repo/issues/new': typeof LayoutOwnerRepoIssuesNewRoute
  '/$owner/$repo/pulls/new': typeof LayoutOwnerRepoPullsNewRoute
  '/$owner/$repo/issues/': typeof LayoutOwnerRepoIssuesIndexRoute
  '/$owner/$repo/pulls/': typeof LayoutOwnerRepoPullsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/repositories': typeof LayoutRepositoriesRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/$owner/$repo/blob': typeof LayoutOwnerRepoBlobRoute
  '/$owner/$repo': typeof LayoutOwnerRepoIndexRoute
  '/$owner/$repo/issues/new': typeof LayoutOwnerRepoIssuesNewRoute
  '/$owner/$repo/pulls/new': typeof LayoutOwnerRepoPullsNewRoute
  '/$owner/$repo/issues': typeof LayoutOwnerRepoIssuesIndexRoute
  '/$owner/$repo/pulls': typeof LayoutOwnerRepoPullsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/repositories': typeof LayoutRepositoriesRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/$owner/$repo/blob': typeof LayoutOwnerRepoBlobRoute
  '/_layout/$owner/$repo/issues': typeof LayoutOwnerRepoIssuesRouteWithChildren
  '/_layout/$owner/$repo/pulls': typeof LayoutOwnerRepoPullsRouteWithChildren
  '/_layout/$owner/$repo/': typeof LayoutOwnerRepoIndexRoute
  '/_layout/$owner/$repo/issues/new': typeof LayoutOwnerRepoIssuesNewRoute
  '/_layout/$owner/$repo/pulls/new': typeof LayoutOwnerRepoPullsNewRoute
  '/_layout/$owner/$repo/issues/': typeof LayoutOwnerRepoIssuesIndexRoute
  '/_layout/$owner/$repo/pulls/': typeof LayoutOwnerRepoPullsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/repositories'
    | '/settings'
    | '/$owner/$repo/blob'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo/'
    | '/$owner/$repo/issues/new'
    | '/$owner/$repo/pulls/new'
    | '/$owner/$repo/issues/'
    | '/$owner/$repo/pulls/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/repositories'
    | '/settings'
    | '/'
    | '/$owner/$repo/blob'
    | '/$owner/$repo'
    | '/$owner/$repo/issues/new'
    | '/$owner/$repo/pulls/new'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pulls'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/repositories'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/$owner/$repo/blob'
    | '/_layout/$owner/$repo/issues'
    | '/_layout/$owner/$repo/pulls'
    | '/_layout/$owner/$repo/'
    | '/_layout/$owner/$repo/issues/new'
    | '/_layout/$owner/$repo/pulls/new'
    | '/_layout/$owner/$repo/issues/'
    | '/_layout/$owner/$repo/pulls/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/repositories': {
      id: '/_layout/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof LayoutRepositoriesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/': {
      id: '/_layout/$owner/$repo/'
      path: '/$owner/$repo'
      fullPath: '/$owner/$repo/'
      preLoaderRoute: typeof LayoutOwnerRepoIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/blob': {
      id: '/_layout/$owner/$repo/blob'
      path: '/$owner/$repo/blob'
      fullPath: '/$owner/$repo/blob'
      preLoaderRoute: typeof LayoutOwnerRepoBlobRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/issues': {
      id: '/_layout/$owner/$repo/issues'
      path: '/$owner/$repo/issues'
      fullPath: '/$owner/$repo/issues'
      preLoaderRoute: typeof LayoutOwnerRepoIssuesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/pulls': {
      id: '/_layout/$owner/$repo/pulls'
      path: '/$owner/$repo/pulls'
      fullPath: '/$owner/$repo/pulls'
      preLoaderRoute: typeof LayoutOwnerRepoPullsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/issues/': {
      id: '/_layout/$owner/$repo/issues/'
      path: '/'
      fullPath: '/$owner/$repo/issues/'
      preLoaderRoute: typeof LayoutOwnerRepoIssuesIndexRouteImport
      parentRoute: typeof LayoutOwnerRepoIssuesRoute
    }
    '/_layout/$owner/$repo/issues/new': {
      id: '/_layout/$owner/$repo/issues/new'
      path: '/new'
      fullPath: '/$owner/$repo/issues/new'
      preLoaderRoute: typeof LayoutOwnerRepoIssuesNewRouteImport
      parentRoute: typeof LayoutOwnerRepoIssuesRoute
    }
    '/_layout/$owner/$repo/pulls/': {
      id: '/_layout/$owner/$repo/pulls/'
      path: '/'
      fullPath: '/$owner/$repo/pulls/'
      preLoaderRoute: typeof LayoutOwnerRepoPullsIndexRouteImport
      parentRoute: typeof LayoutOwnerRepoPullsRoute
    }
    '/_layout/$owner/$repo/pulls/new': {
      id: '/_layout/$owner/$repo/pulls/new'
      path: '/new'
      fullPath: '/$owner/$repo/pulls/new'
      preLoaderRoute: typeof LayoutOwnerRepoPullsNewRouteImport
      parentRoute: typeof LayoutOwnerRepoPullsRoute
    }
  }
}

interface LayoutOwnerRepoIssuesRouteChildren {
  LayoutOwnerRepoIssuesNewRoute: typeof LayoutOwnerRepoIssuesNewRoute
  LayoutOwnerRepoIssuesIndexRoute: typeof LayoutOwnerRepoIssuesIndexRoute
}

const LayoutOwnerRepoIssuesRouteChildren: LayoutOwnerRepoIssuesRouteChildren = {
  LayoutOwnerRepoIssuesNewRoute: LayoutOwnerRepoIssuesNewRoute,
  LayoutOwnerRepoIssuesIndexRoute: LayoutOwnerRepoIssuesIndexRoute,
}

const LayoutOwnerRepoIssuesRouteWithChildren =
  LayoutOwnerRepoIssuesRoute._addFileChildren(
    LayoutOwnerRepoIssuesRouteChildren,
  )

interface LayoutOwnerRepoPullsRouteChildren {
  LayoutOwnerRepoPullsNewRoute: typeof LayoutOwnerRepoPullsNewRoute
  LayoutOwnerRepoPullsIndexRoute: typeof LayoutOwnerRepoPullsIndexRoute
}

const LayoutOwnerRepoPullsRouteChildren: LayoutOwnerRepoPullsRouteChildren = {
  LayoutOwnerRepoPullsNewRoute: LayoutOwnerRepoPullsNewRoute,
  LayoutOwnerRepoPullsIndexRoute: LayoutOwnerRepoPullsIndexRoute,
}

const LayoutOwnerRepoPullsRouteWithChildren =
  LayoutOwnerRepoPullsRoute._addFileChildren(LayoutOwnerRepoPullsRouteChildren)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutRepositoriesRoute: typeof LayoutRepositoriesRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutOwnerRepoBlobRoute: typeof LayoutOwnerRepoBlobRoute
  LayoutOwnerRepoIssuesRoute: typeof LayoutOwnerRepoIssuesRouteWithChildren
  LayoutOwnerRepoPullsRoute: typeof LayoutOwnerRepoPullsRouteWithChildren
  LayoutOwnerRepoIndexRoute: typeof LayoutOwnerRepoIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutRepositoriesRoute: LayoutRepositoriesRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutOwnerRepoBlobRoute: LayoutOwnerRepoBlobRoute,
  LayoutOwnerRepoIssuesRoute: LayoutOwnerRepoIssuesRouteWithChildren,
  LayoutOwnerRepoPullsRoute: LayoutOwnerRepoPullsRouteWithChildren,
  LayoutOwnerRepoIndexRoute: LayoutOwnerRepoIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
