/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutExploreRouteImport } from './routes/_layout/explore'
import { Route as LayoutRepositoriesRouteImport } from './routes/_layout/repositories'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutProfileUsernameRouteImport } from './routes/_layout/profile.$username'
import { Route as LayoutOwnerRepoIndexRouteImport } from './routes/_layout/$owner/$repo/index'
import { Route as LayoutOwnerRepoActivityRouteImport } from './routes/_layout/$owner/$repo/activity'
import { Route as LayoutOwnerRepoBranchesRouteImport } from './routes/_layout/$owner/$repo/branches'
import { Route as LayoutOwnerRepoCommitRouteImport } from './routes/_layout/$owner/$repo/commit'
import { Route as LayoutOwnerRepoCommitsRouteImport } from './routes/_layout/$owner/$repo/commits'
import { Route as LayoutOwnerRepoForksRouteImport } from './routes/_layout/$owner/$repo/forks'
import { Route as LayoutOwnerRepoIssuesRouteImport } from './routes/_layout/$owner/$repo/issues'
import { Route as LayoutOwnerRepoPullsRouteImport } from './routes/_layout/$owner/$repo/pulls'
import { Route as LayoutOwnerRepoReleasesRouteImport } from './routes/_layout/$owner/$repo/releases'
import { Route as LayoutOwnerRepoSettingsRouteImport } from './routes/_layout/$owner/$repo/settings'
import { Route as LayoutOwnerRepoStarsRouteImport } from './routes/_layout/$owner/$repo/stars'
import { Route as LayoutOwnerRepoWatchersRouteImport } from './routes/_layout/$owner/$repo/watchers'
import { Route as LayoutOwnerRepoBlameSplatRouteImport } from './routes/_layout/$owner/$repo/blame.$'
import { Route as LayoutOwnerRepoCommitHashRouteImport } from './routes/_layout/$owner/$repo/commit.$hash'
import { Route as LayoutOwnerRepoCommitsIndexRouteImport } from './routes/_layout/$owner/$repo/commits.index'
import { Route as LayoutOwnerRepoIssuesIndexRouteImport } from './routes/_layout/$owner/$repo/issues.index'
import { Route as LayoutOwnerRepoIssuesNumberRouteImport } from './routes/_layout/$owner/$repo/issues.$number'
import { Route as LayoutOwnerRepoIssuesNewRouteImport } from './routes/_layout/$owner/$repo/issues.new'
import { Route as LayoutOwnerRepoPullsIndexRouteImport } from './routes/_layout/$owner/$repo/pulls.index'
import { Route as LayoutOwnerRepoPullsNumberRouteImport } from './routes/_layout/$owner/$repo/pulls.$number'
import { Route as LayoutOwnerRepoPullsNewRouteImport } from './routes/_layout/$owner/$repo/pulls.new'
import { Route as LayoutOwnerRepoCommitsBranchBranchRouteImport } from './routes/_layout/$owner/$repo/commits.branch.$branch'
import { Route as LayoutOwnerRepoSrcBranchBranchRouteImport } from './routes/_layout/$owner/$repo/src.branch.$branch'
import { Route as LayoutOwnerRepoSrcCommitShaRouteImport } from './routes/_layout/$owner/$repo/src.commit.$sha'
import { Route as LayoutOwnerRepoSrcBranchBranchIndexRouteImport } from './routes/_layout/$owner/$repo/src.branch.$branch.index'
import { Route as LayoutOwnerRepoSrcBranchBranchSplatRouteImport } from './routes/_layout/$owner/$repo/src.branch.$branch.$'
import { Route as LayoutOwnerRepoSrcCommitShaIndexRouteImport } from './routes/_layout/$owner/$repo/src.commit.$sha.index'
import { Route as LayoutOwnerRepoSrcCommitShaSplatRouteImport } from './routes/_layout/$owner/$repo/src.commit.$sha.$'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExploreRoute = LayoutExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRepositoriesRoute = LayoutRepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileUsernameRoute = LayoutProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnerRepoIndexRoute = LayoutOwnerRepoIndexRouteImport.update({
  id: '/$owner/$repo/',
  path: '/$owner/$repo/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnerRepoActivityRoute = LayoutOwnerRepoActivityRouteImport.update({
  id: '/$owner/$repo/activity',
  path: '/$owner/$repo/activity',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnerRepoBranchesRoute = LayoutOwnerRepoBranchesRouteImport.update({
  id: '/$owner/$repo/branches',
  path: '/$owner/$repo/branches',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnerRepoCommitRoute = LayoutOwnerRepoCommitRouteImport.update({
  id: '/$owner/$repo/commit',
  path: '/$owner/$repo/commit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnerRepoCommitsRoute = LayoutOwnerRepoCommitsRouteImport.update({
  id: '/$owner/$repo/commits',
  path: '/$owner/$repo/commits',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnerRepoForksRoute = LayoutOwnerRepoForksRouteImport.update({
  id: '/$owner/$repo/forks',
  path: '/$owner/$repo/forks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnerRepoIssuesRoute = LayoutOwnerRepoIssuesRouteImport.update({
  id: '/$owner/$repo/issues',
  path: '/$owner/$repo/issues',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnerRepoPullsRoute = LayoutOwnerRepoPullsRouteImport.update({
  id: '/$owner/$repo/pulls',
  path: '/$owner/$repo/pulls',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnerRepoReleasesRoute = LayoutOwnerRepoReleasesRouteImport.update({
  id: '/$owner/$repo/releases',
  path: '/$owner/$repo/releases',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnerRepoSettingsRoute = LayoutOwnerRepoSettingsRouteImport.update({
  id: '/$owner/$repo/settings',
  path: '/$owner/$repo/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnerRepoStarsRoute = LayoutOwnerRepoStarsRouteImport.update({
  id: '/$owner/$repo/stars',
  path: '/$owner/$repo/stars',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnerRepoWatchersRoute = LayoutOwnerRepoWatchersRouteImport.update({
  id: '/$owner/$repo/watchers',
  path: '/$owner/$repo/watchers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnerRepoBlameSplatRoute =
  LayoutOwnerRepoBlameSplatRouteImport.update({
    id: '/$owner/$repo/blame/$',
    path: '/$owner/$repo/blame/$',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutOwnerRepoCommitHashRoute =
  LayoutOwnerRepoCommitHashRouteImport.update({
    id: '/$hash',
    path: '/$hash',
    getParentRoute: () => LayoutOwnerRepoCommitRoute,
  } as any)
const LayoutOwnerRepoCommitsIndexRoute =
  LayoutOwnerRepoCommitsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutOwnerRepoCommitsRoute,
  } as any)
const LayoutOwnerRepoIssuesIndexRoute =
  LayoutOwnerRepoIssuesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutOwnerRepoIssuesRoute,
  } as any)
const LayoutOwnerRepoIssuesNumberRoute =
  LayoutOwnerRepoIssuesNumberRouteImport.update({
    id: '/$number',
    path: '/$number',
    getParentRoute: () => LayoutOwnerRepoIssuesRoute,
  } as any)
const LayoutOwnerRepoIssuesNewRoute =
  LayoutOwnerRepoIssuesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => LayoutOwnerRepoIssuesRoute,
  } as any)
const LayoutOwnerRepoPullsIndexRoute =
  LayoutOwnerRepoPullsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutOwnerRepoPullsRoute,
  } as any)
const LayoutOwnerRepoPullsNumberRoute =
  LayoutOwnerRepoPullsNumberRouteImport.update({
    id: '/$number',
    path: '/$number',
    getParentRoute: () => LayoutOwnerRepoPullsRoute,
  } as any)
const LayoutOwnerRepoPullsNewRoute = LayoutOwnerRepoPullsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LayoutOwnerRepoPullsRoute,
} as any)
const LayoutOwnerRepoCommitsBranchBranchRoute =
  LayoutOwnerRepoCommitsBranchBranchRouteImport.update({
    id: '/branch/$branch',
    path: '/branch/$branch',
    getParentRoute: () => LayoutOwnerRepoCommitsRoute,
  } as any)
const LayoutOwnerRepoSrcBranchBranchRoute =
  LayoutOwnerRepoSrcBranchBranchRouteImport.update({
    id: '/$owner/$repo/src/branch/$branch',
    path: '/$owner/$repo/src/branch/$branch',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutOwnerRepoSrcCommitShaRoute =
  LayoutOwnerRepoSrcCommitShaRouteImport.update({
    id: '/$owner/$repo/src/commit/$sha',
    path: '/$owner/$repo/src/commit/$sha',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutOwnerRepoSrcBranchBranchIndexRoute =
  LayoutOwnerRepoSrcBranchBranchIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutOwnerRepoSrcBranchBranchRoute,
  } as any)
const LayoutOwnerRepoSrcBranchBranchSplatRoute =
  LayoutOwnerRepoSrcBranchBranchSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => LayoutOwnerRepoSrcBranchBranchRoute,
  } as any)
const LayoutOwnerRepoSrcCommitShaIndexRoute =
  LayoutOwnerRepoSrcCommitShaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutOwnerRepoSrcCommitShaRoute,
  } as any)
const LayoutOwnerRepoSrcCommitShaSplatRoute =
  LayoutOwnerRepoSrcCommitShaSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => LayoutOwnerRepoSrcCommitShaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/explore': typeof LayoutExploreRoute
  '/repositories': typeof LayoutRepositoriesRoute
  '/settings': typeof LayoutSettingsRoute
  '/profile/$username': typeof LayoutProfileUsernameRoute
  '/$owner/$repo/activity': typeof LayoutOwnerRepoActivityRoute
  '/$owner/$repo/branches': typeof LayoutOwnerRepoBranchesRoute
  '/$owner/$repo/commit': typeof LayoutOwnerRepoCommitRouteWithChildren
  '/$owner/$repo/commits': typeof LayoutOwnerRepoCommitsRouteWithChildren
  '/$owner/$repo/forks': typeof LayoutOwnerRepoForksRoute
  '/$owner/$repo/issues': typeof LayoutOwnerRepoIssuesRouteWithChildren
  '/$owner/$repo/pulls': typeof LayoutOwnerRepoPullsRouteWithChildren
  '/$owner/$repo/releases': typeof LayoutOwnerRepoReleasesRoute
  '/$owner/$repo/settings': typeof LayoutOwnerRepoSettingsRoute
  '/$owner/$repo/stars': typeof LayoutOwnerRepoStarsRoute
  '/$owner/$repo/watchers': typeof LayoutOwnerRepoWatchersRoute
  '/$owner/$repo/': typeof LayoutOwnerRepoIndexRoute
  '/$owner/$repo/blame/$': typeof LayoutOwnerRepoBlameSplatRoute
  '/$owner/$repo/commit/$hash': typeof LayoutOwnerRepoCommitHashRoute
  '/$owner/$repo/issues/$number': typeof LayoutOwnerRepoIssuesNumberRoute
  '/$owner/$repo/issues/new': typeof LayoutOwnerRepoIssuesNewRoute
  '/$owner/$repo/pulls/$number': typeof LayoutOwnerRepoPullsNumberRoute
  '/$owner/$repo/pulls/new': typeof LayoutOwnerRepoPullsNewRoute
  '/$owner/$repo/commits/': typeof LayoutOwnerRepoCommitsIndexRoute
  '/$owner/$repo/issues/': typeof LayoutOwnerRepoIssuesIndexRoute
  '/$owner/$repo/pulls/': typeof LayoutOwnerRepoPullsIndexRoute
  '/$owner/$repo/commits/branch/$branch': typeof LayoutOwnerRepoCommitsBranchBranchRoute
  '/$owner/$repo/src/branch/$branch': typeof LayoutOwnerRepoSrcBranchBranchRouteWithChildren
  '/$owner/$repo/src/commit/$sha': typeof LayoutOwnerRepoSrcCommitShaRouteWithChildren
  '/$owner/$repo/src/branch/$branch/$': typeof LayoutOwnerRepoSrcBranchBranchSplatRoute
  '/$owner/$repo/src/commit/$sha/$': typeof LayoutOwnerRepoSrcCommitShaSplatRoute
  '/$owner/$repo/src/branch/$branch/': typeof LayoutOwnerRepoSrcBranchBranchIndexRoute
  '/$owner/$repo/src/commit/$sha/': typeof LayoutOwnerRepoSrcCommitShaIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/explore': typeof LayoutExploreRoute
  '/repositories': typeof LayoutRepositoriesRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/profile/$username': typeof LayoutProfileUsernameRoute
  '/$owner/$repo/activity': typeof LayoutOwnerRepoActivityRoute
  '/$owner/$repo/branches': typeof LayoutOwnerRepoBranchesRoute
  '/$owner/$repo/commit': typeof LayoutOwnerRepoCommitRouteWithChildren
  '/$owner/$repo/forks': typeof LayoutOwnerRepoForksRoute
  '/$owner/$repo/releases': typeof LayoutOwnerRepoReleasesRoute
  '/$owner/$repo/settings': typeof LayoutOwnerRepoSettingsRoute
  '/$owner/$repo/stars': typeof LayoutOwnerRepoStarsRoute
  '/$owner/$repo/watchers': typeof LayoutOwnerRepoWatchersRoute
  '/$owner/$repo': typeof LayoutOwnerRepoIndexRoute
  '/$owner/$repo/blame/$': typeof LayoutOwnerRepoBlameSplatRoute
  '/$owner/$repo/commit/$hash': typeof LayoutOwnerRepoCommitHashRoute
  '/$owner/$repo/issues/$number': typeof LayoutOwnerRepoIssuesNumberRoute
  '/$owner/$repo/issues/new': typeof LayoutOwnerRepoIssuesNewRoute
  '/$owner/$repo/pulls/$number': typeof LayoutOwnerRepoPullsNumberRoute
  '/$owner/$repo/pulls/new': typeof LayoutOwnerRepoPullsNewRoute
  '/$owner/$repo/commits': typeof LayoutOwnerRepoCommitsIndexRoute
  '/$owner/$repo/issues': typeof LayoutOwnerRepoIssuesIndexRoute
  '/$owner/$repo/pulls': typeof LayoutOwnerRepoPullsIndexRoute
  '/$owner/$repo/commits/branch/$branch': typeof LayoutOwnerRepoCommitsBranchBranchRoute
  '/$owner/$repo/src/branch/$branch/$': typeof LayoutOwnerRepoSrcBranchBranchSplatRoute
  '/$owner/$repo/src/commit/$sha/$': typeof LayoutOwnerRepoSrcCommitShaSplatRoute
  '/$owner/$repo/src/branch/$branch': typeof LayoutOwnerRepoSrcBranchBranchIndexRoute
  '/$owner/$repo/src/commit/$sha': typeof LayoutOwnerRepoSrcCommitShaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/explore': typeof LayoutExploreRoute
  '/_layout/repositories': typeof LayoutRepositoriesRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/profile/$username': typeof LayoutProfileUsernameRoute
  '/_layout/$owner/$repo/activity': typeof LayoutOwnerRepoActivityRoute
  '/_layout/$owner/$repo/branches': typeof LayoutOwnerRepoBranchesRoute
  '/_layout/$owner/$repo/commit': typeof LayoutOwnerRepoCommitRouteWithChildren
  '/_layout/$owner/$repo/commits': typeof LayoutOwnerRepoCommitsRouteWithChildren
  '/_layout/$owner/$repo/forks': typeof LayoutOwnerRepoForksRoute
  '/_layout/$owner/$repo/issues': typeof LayoutOwnerRepoIssuesRouteWithChildren
  '/_layout/$owner/$repo/pulls': typeof LayoutOwnerRepoPullsRouteWithChildren
  '/_layout/$owner/$repo/releases': typeof LayoutOwnerRepoReleasesRoute
  '/_layout/$owner/$repo/settings': typeof LayoutOwnerRepoSettingsRoute
  '/_layout/$owner/$repo/stars': typeof LayoutOwnerRepoStarsRoute
  '/_layout/$owner/$repo/watchers': typeof LayoutOwnerRepoWatchersRoute
  '/_layout/$owner/$repo/': typeof LayoutOwnerRepoIndexRoute
  '/_layout/$owner/$repo/blame/$': typeof LayoutOwnerRepoBlameSplatRoute
  '/_layout/$owner/$repo/commit/$hash': typeof LayoutOwnerRepoCommitHashRoute
  '/_layout/$owner/$repo/issues/$number': typeof LayoutOwnerRepoIssuesNumberRoute
  '/_layout/$owner/$repo/issues/new': typeof LayoutOwnerRepoIssuesNewRoute
  '/_layout/$owner/$repo/pulls/$number': typeof LayoutOwnerRepoPullsNumberRoute
  '/_layout/$owner/$repo/pulls/new': typeof LayoutOwnerRepoPullsNewRoute
  '/_layout/$owner/$repo/commits/': typeof LayoutOwnerRepoCommitsIndexRoute
  '/_layout/$owner/$repo/issues/': typeof LayoutOwnerRepoIssuesIndexRoute
  '/_layout/$owner/$repo/pulls/': typeof LayoutOwnerRepoPullsIndexRoute
  '/_layout/$owner/$repo/commits/branch/$branch': typeof LayoutOwnerRepoCommitsBranchBranchRoute
  '/_layout/$owner/$repo/src/branch/$branch': typeof LayoutOwnerRepoSrcBranchBranchRouteWithChildren
  '/_layout/$owner/$repo/src/commit/$sha': typeof LayoutOwnerRepoSrcCommitShaRouteWithChildren
  '/_layout/$owner/$repo/src/branch/$branch/$': typeof LayoutOwnerRepoSrcBranchBranchSplatRoute
  '/_layout/$owner/$repo/src/commit/$sha/$': typeof LayoutOwnerRepoSrcCommitShaSplatRoute
  '/_layout/$owner/$repo/src/branch/$branch/': typeof LayoutOwnerRepoSrcBranchBranchIndexRoute
  '/_layout/$owner/$repo/src/commit/$sha/': typeof LayoutOwnerRepoSrcCommitShaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/explore'
    | '/repositories'
    | '/settings'
    | '/profile/$username'
    | '/$owner/$repo/activity'
    | '/$owner/$repo/branches'
    | '/$owner/$repo/commit'
    | '/$owner/$repo/commits'
    | '/$owner/$repo/forks'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo/releases'
    | '/$owner/$repo/settings'
    | '/$owner/$repo/stars'
    | '/$owner/$repo/watchers'
    | '/$owner/$repo/'
    | '/$owner/$repo/blame/$'
    | '/$owner/$repo/commit/$hash'
    | '/$owner/$repo/issues/$number'
    | '/$owner/$repo/issues/new'
    | '/$owner/$repo/pulls/$number'
    | '/$owner/$repo/pulls/new'
    | '/$owner/$repo/commits/'
    | '/$owner/$repo/issues/'
    | '/$owner/$repo/pulls/'
    | '/$owner/$repo/commits/branch/$branch'
    | '/$owner/$repo/src/branch/$branch'
    | '/$owner/$repo/src/commit/$sha'
    | '/$owner/$repo/src/branch/$branch/$'
    | '/$owner/$repo/src/commit/$sha/$'
    | '/$owner/$repo/src/branch/$branch/'
    | '/$owner/$repo/src/commit/$sha/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/explore'
    | '/repositories'
    | '/settings'
    | '/'
    | '/profile/$username'
    | '/$owner/$repo/activity'
    | '/$owner/$repo/branches'
    | '/$owner/$repo/commit'
    | '/$owner/$repo/forks'
    | '/$owner/$repo/releases'
    | '/$owner/$repo/settings'
    | '/$owner/$repo/stars'
    | '/$owner/$repo/watchers'
    | '/$owner/$repo'
    | '/$owner/$repo/blame/$'
    | '/$owner/$repo/commit/$hash'
    | '/$owner/$repo/issues/$number'
    | '/$owner/$repo/issues/new'
    | '/$owner/$repo/pulls/$number'
    | '/$owner/$repo/pulls/new'
    | '/$owner/$repo/commits'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo/commits/branch/$branch'
    | '/$owner/$repo/src/branch/$branch/$'
    | '/$owner/$repo/src/commit/$sha/$'
    | '/$owner/$repo/src/branch/$branch'
    | '/$owner/$repo/src/commit/$sha'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/explore'
    | '/_layout/repositories'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/profile/$username'
    | '/_layout/$owner/$repo/activity'
    | '/_layout/$owner/$repo/branches'
    | '/_layout/$owner/$repo/commit'
    | '/_layout/$owner/$repo/commits'
    | '/_layout/$owner/$repo/forks'
    | '/_layout/$owner/$repo/issues'
    | '/_layout/$owner/$repo/pulls'
    | '/_layout/$owner/$repo/releases'
    | '/_layout/$owner/$repo/settings'
    | '/_layout/$owner/$repo/stars'
    | '/_layout/$owner/$repo/watchers'
    | '/_layout/$owner/$repo/'
    | '/_layout/$owner/$repo/blame/$'
    | '/_layout/$owner/$repo/commit/$hash'
    | '/_layout/$owner/$repo/issues/$number'
    | '/_layout/$owner/$repo/issues/new'
    | '/_layout/$owner/$repo/pulls/$number'
    | '/_layout/$owner/$repo/pulls/new'
    | '/_layout/$owner/$repo/commits/'
    | '/_layout/$owner/$repo/issues/'
    | '/_layout/$owner/$repo/pulls/'
    | '/_layout/$owner/$repo/commits/branch/$branch'
    | '/_layout/$owner/$repo/src/branch/$branch'
    | '/_layout/$owner/$repo/src/commit/$sha'
    | '/_layout/$owner/$repo/src/branch/$branch/$'
    | '/_layout/$owner/$repo/src/commit/$sha/$'
    | '/_layout/$owner/$repo/src/branch/$branch/'
    | '/_layout/$owner/$repo/src/commit/$sha/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/explore': {
      id: '/_layout/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof LayoutExploreRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/repositories': {
      id: '/_layout/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof LayoutRepositoriesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile/$username': {
      id: '/_layout/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof LayoutProfileUsernameRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/': {
      id: '/_layout/$owner/$repo/'
      path: '/$owner/$repo'
      fullPath: '/$owner/$repo/'
      preLoaderRoute: typeof LayoutOwnerRepoIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/activity': {
      id: '/_layout/$owner/$repo/activity'
      path: '/$owner/$repo/activity'
      fullPath: '/$owner/$repo/activity'
      preLoaderRoute: typeof LayoutOwnerRepoActivityRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/branches': {
      id: '/_layout/$owner/$repo/branches'
      path: '/$owner/$repo/branches'
      fullPath: '/$owner/$repo/branches'
      preLoaderRoute: typeof LayoutOwnerRepoBranchesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/commit': {
      id: '/_layout/$owner/$repo/commit'
      path: '/$owner/$repo/commit'
      fullPath: '/$owner/$repo/commit'
      preLoaderRoute: typeof LayoutOwnerRepoCommitRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/commits': {
      id: '/_layout/$owner/$repo/commits'
      path: '/$owner/$repo/commits'
      fullPath: '/$owner/$repo/commits'
      preLoaderRoute: typeof LayoutOwnerRepoCommitsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/forks': {
      id: '/_layout/$owner/$repo/forks'
      path: '/$owner/$repo/forks'
      fullPath: '/$owner/$repo/forks'
      preLoaderRoute: typeof LayoutOwnerRepoForksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/issues': {
      id: '/_layout/$owner/$repo/issues'
      path: '/$owner/$repo/issues'
      fullPath: '/$owner/$repo/issues'
      preLoaderRoute: typeof LayoutOwnerRepoIssuesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/pulls': {
      id: '/_layout/$owner/$repo/pulls'
      path: '/$owner/$repo/pulls'
      fullPath: '/$owner/$repo/pulls'
      preLoaderRoute: typeof LayoutOwnerRepoPullsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/releases': {
      id: '/_layout/$owner/$repo/releases'
      path: '/$owner/$repo/releases'
      fullPath: '/$owner/$repo/releases'
      preLoaderRoute: typeof LayoutOwnerRepoReleasesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/settings': {
      id: '/_layout/$owner/$repo/settings'
      path: '/$owner/$repo/settings'
      fullPath: '/$owner/$repo/settings'
      preLoaderRoute: typeof LayoutOwnerRepoSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/stars': {
      id: '/_layout/$owner/$repo/stars'
      path: '/$owner/$repo/stars'
      fullPath: '/$owner/$repo/stars'
      preLoaderRoute: typeof LayoutOwnerRepoStarsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/watchers': {
      id: '/_layout/$owner/$repo/watchers'
      path: '/$owner/$repo/watchers'
      fullPath: '/$owner/$repo/watchers'
      preLoaderRoute: typeof LayoutOwnerRepoWatchersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/blame/$': {
      id: '/_layout/$owner/$repo/blame/$'
      path: '/$owner/$repo/blame/$'
      fullPath: '/$owner/$repo/blame/$'
      preLoaderRoute: typeof LayoutOwnerRepoBlameSplatRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/commit/$hash': {
      id: '/_layout/$owner/$repo/commit/$hash'
      path: '/$hash'
      fullPath: '/$owner/$repo/commit/$hash'
      preLoaderRoute: typeof LayoutOwnerRepoCommitHashRouteImport
      parentRoute: typeof LayoutOwnerRepoCommitRoute
    }
    '/_layout/$owner/$repo/commits/': {
      id: '/_layout/$owner/$repo/commits/'
      path: '/'
      fullPath: '/$owner/$repo/commits/'
      preLoaderRoute: typeof LayoutOwnerRepoCommitsIndexRouteImport
      parentRoute: typeof LayoutOwnerRepoCommitsRoute
    }
    '/_layout/$owner/$repo/issues/': {
      id: '/_layout/$owner/$repo/issues/'
      path: '/'
      fullPath: '/$owner/$repo/issues/'
      preLoaderRoute: typeof LayoutOwnerRepoIssuesIndexRouteImport
      parentRoute: typeof LayoutOwnerRepoIssuesRoute
    }
    '/_layout/$owner/$repo/issues/$number': {
      id: '/_layout/$owner/$repo/issues/$number'
      path: '/$number'
      fullPath: '/$owner/$repo/issues/$number'
      preLoaderRoute: typeof LayoutOwnerRepoIssuesNumberRouteImport
      parentRoute: typeof LayoutOwnerRepoIssuesRoute
    }
    '/_layout/$owner/$repo/issues/new': {
      id: '/_layout/$owner/$repo/issues/new'
      path: '/new'
      fullPath: '/$owner/$repo/issues/new'
      preLoaderRoute: typeof LayoutOwnerRepoIssuesNewRouteImport
      parentRoute: typeof LayoutOwnerRepoIssuesRoute
    }
    '/_layout/$owner/$repo/pulls/': {
      id: '/_layout/$owner/$repo/pulls/'
      path: '/'
      fullPath: '/$owner/$repo/pulls/'
      preLoaderRoute: typeof LayoutOwnerRepoPullsIndexRouteImport
      parentRoute: typeof LayoutOwnerRepoPullsRoute
    }
    '/_layout/$owner/$repo/pulls/$number': {
      id: '/_layout/$owner/$repo/pulls/$number'
      path: '/$number'
      fullPath: '/$owner/$repo/pulls/$number'
      preLoaderRoute: typeof LayoutOwnerRepoPullsNumberRouteImport
      parentRoute: typeof LayoutOwnerRepoPullsRoute
    }
    '/_layout/$owner/$repo/pulls/new': {
      id: '/_layout/$owner/$repo/pulls/new'
      path: '/new'
      fullPath: '/$owner/$repo/pulls/new'
      preLoaderRoute: typeof LayoutOwnerRepoPullsNewRouteImport
      parentRoute: typeof LayoutOwnerRepoPullsRoute
    }
    '/_layout/$owner/$repo/commits/branch/$branch': {
      id: '/_layout/$owner/$repo/commits/branch/$branch'
      path: '/branch/$branch'
      fullPath: '/$owner/$repo/commits/branch/$branch'
      preLoaderRoute: typeof LayoutOwnerRepoCommitsBranchBranchRouteImport
      parentRoute: typeof LayoutOwnerRepoCommitsRoute
    }
    '/_layout/$owner/$repo/src/branch/$branch': {
      id: '/_layout/$owner/$repo/src/branch/$branch'
      path: '/$owner/$repo/src/branch/$branch'
      fullPath: '/$owner/$repo/src/branch/$branch'
      preLoaderRoute: typeof LayoutOwnerRepoSrcBranchBranchRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/src/commit/$sha': {
      id: '/_layout/$owner/$repo/src/commit/$sha'
      path: '/$owner/$repo/src/commit/$sha'
      fullPath: '/$owner/$repo/src/commit/$sha'
      preLoaderRoute: typeof LayoutOwnerRepoSrcCommitShaRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/src/branch/$branch/': {
      id: '/_layout/$owner/$repo/src/branch/$branch/'
      path: '/'
      fullPath: '/$owner/$repo/src/branch/$branch/'
      preLoaderRoute: typeof LayoutOwnerRepoSrcBranchBranchIndexRouteImport
      parentRoute: typeof LayoutOwnerRepoSrcBranchBranchRoute
    }
    '/_layout/$owner/$repo/src/branch/$branch/$': {
      id: '/_layout/$owner/$repo/src/branch/$branch/$'
      path: '/$'
      fullPath: '/$owner/$repo/src/branch/$branch/$'
      preLoaderRoute: typeof LayoutOwnerRepoSrcBranchBranchSplatRouteImport
      parentRoute: typeof LayoutOwnerRepoSrcBranchBranchRoute
    }
    '/_layout/$owner/$repo/src/commit/$sha/': {
      id: '/_layout/$owner/$repo/src/commit/$sha/'
      path: '/'
      fullPath: '/$owner/$repo/src/commit/$sha/'
      preLoaderRoute: typeof LayoutOwnerRepoSrcCommitShaIndexRouteImport
      parentRoute: typeof LayoutOwnerRepoSrcCommitShaRoute
    }
    '/_layout/$owner/$repo/src/commit/$sha/$': {
      id: '/_layout/$owner/$repo/src/commit/$sha/$'
      path: '/$'
      fullPath: '/$owner/$repo/src/commit/$sha/$'
      preLoaderRoute: typeof LayoutOwnerRepoSrcCommitShaSplatRouteImport
      parentRoute: typeof LayoutOwnerRepoSrcCommitShaRoute
    }
  }
}

interface LayoutOwnerRepoCommitRouteChildren {
  LayoutOwnerRepoCommitHashRoute: typeof LayoutOwnerRepoCommitHashRoute
}

const LayoutOwnerRepoCommitRouteChildren: LayoutOwnerRepoCommitRouteChildren = {
  LayoutOwnerRepoCommitHashRoute: LayoutOwnerRepoCommitHashRoute,
}

const LayoutOwnerRepoCommitRouteWithChildren =
  LayoutOwnerRepoCommitRoute._addFileChildren(
    LayoutOwnerRepoCommitRouteChildren,
  )

interface LayoutOwnerRepoCommitsRouteChildren {
  LayoutOwnerRepoCommitsIndexRoute: typeof LayoutOwnerRepoCommitsIndexRoute
  LayoutOwnerRepoCommitsBranchBranchRoute: typeof LayoutOwnerRepoCommitsBranchBranchRoute
}

const LayoutOwnerRepoCommitsRouteChildren: LayoutOwnerRepoCommitsRouteChildren =
  {
    LayoutOwnerRepoCommitsIndexRoute: LayoutOwnerRepoCommitsIndexRoute,
    LayoutOwnerRepoCommitsBranchBranchRoute:
      LayoutOwnerRepoCommitsBranchBranchRoute,
  }

const LayoutOwnerRepoCommitsRouteWithChildren =
  LayoutOwnerRepoCommitsRoute._addFileChildren(
    LayoutOwnerRepoCommitsRouteChildren,
  )

interface LayoutOwnerRepoIssuesRouteChildren {
  LayoutOwnerRepoIssuesNumberRoute: typeof LayoutOwnerRepoIssuesNumberRoute
  LayoutOwnerRepoIssuesNewRoute: typeof LayoutOwnerRepoIssuesNewRoute
  LayoutOwnerRepoIssuesIndexRoute: typeof LayoutOwnerRepoIssuesIndexRoute
}

const LayoutOwnerRepoIssuesRouteChildren: LayoutOwnerRepoIssuesRouteChildren = {
  LayoutOwnerRepoIssuesNumberRoute: LayoutOwnerRepoIssuesNumberRoute,
  LayoutOwnerRepoIssuesNewRoute: LayoutOwnerRepoIssuesNewRoute,
  LayoutOwnerRepoIssuesIndexRoute: LayoutOwnerRepoIssuesIndexRoute,
}

const LayoutOwnerRepoIssuesRouteWithChildren =
  LayoutOwnerRepoIssuesRoute._addFileChildren(
    LayoutOwnerRepoIssuesRouteChildren,
  )

interface LayoutOwnerRepoPullsRouteChildren {
  LayoutOwnerRepoPullsNumberRoute: typeof LayoutOwnerRepoPullsNumberRoute
  LayoutOwnerRepoPullsNewRoute: typeof LayoutOwnerRepoPullsNewRoute
  LayoutOwnerRepoPullsIndexRoute: typeof LayoutOwnerRepoPullsIndexRoute
}

const LayoutOwnerRepoPullsRouteChildren: LayoutOwnerRepoPullsRouteChildren = {
  LayoutOwnerRepoPullsNumberRoute: LayoutOwnerRepoPullsNumberRoute,
  LayoutOwnerRepoPullsNewRoute: LayoutOwnerRepoPullsNewRoute,
  LayoutOwnerRepoPullsIndexRoute: LayoutOwnerRepoPullsIndexRoute,
}

const LayoutOwnerRepoPullsRouteWithChildren =
  LayoutOwnerRepoPullsRoute._addFileChildren(LayoutOwnerRepoPullsRouteChildren)

interface LayoutOwnerRepoSrcBranchBranchRouteChildren {
  LayoutOwnerRepoSrcBranchBranchSplatRoute: typeof LayoutOwnerRepoSrcBranchBranchSplatRoute
  LayoutOwnerRepoSrcBranchBranchIndexRoute: typeof LayoutOwnerRepoSrcBranchBranchIndexRoute
}

const LayoutOwnerRepoSrcBranchBranchRouteChildren: LayoutOwnerRepoSrcBranchBranchRouteChildren =
  {
    LayoutOwnerRepoSrcBranchBranchSplatRoute:
      LayoutOwnerRepoSrcBranchBranchSplatRoute,
    LayoutOwnerRepoSrcBranchBranchIndexRoute:
      LayoutOwnerRepoSrcBranchBranchIndexRoute,
  }

const LayoutOwnerRepoSrcBranchBranchRouteWithChildren =
  LayoutOwnerRepoSrcBranchBranchRoute._addFileChildren(
    LayoutOwnerRepoSrcBranchBranchRouteChildren,
  )

interface LayoutOwnerRepoSrcCommitShaRouteChildren {
  LayoutOwnerRepoSrcCommitShaSplatRoute: typeof LayoutOwnerRepoSrcCommitShaSplatRoute
  LayoutOwnerRepoSrcCommitShaIndexRoute: typeof LayoutOwnerRepoSrcCommitShaIndexRoute
}

const LayoutOwnerRepoSrcCommitShaRouteChildren: LayoutOwnerRepoSrcCommitShaRouteChildren =
  {
    LayoutOwnerRepoSrcCommitShaSplatRoute:
      LayoutOwnerRepoSrcCommitShaSplatRoute,
    LayoutOwnerRepoSrcCommitShaIndexRoute:
      LayoutOwnerRepoSrcCommitShaIndexRoute,
  }

const LayoutOwnerRepoSrcCommitShaRouteWithChildren =
  LayoutOwnerRepoSrcCommitShaRoute._addFileChildren(
    LayoutOwnerRepoSrcCommitShaRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutExploreRoute: typeof LayoutExploreRoute
  LayoutRepositoriesRoute: typeof LayoutRepositoriesRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProfileUsernameRoute: typeof LayoutProfileUsernameRoute
  LayoutOwnerRepoActivityRoute: typeof LayoutOwnerRepoActivityRoute
  LayoutOwnerRepoBranchesRoute: typeof LayoutOwnerRepoBranchesRoute
  LayoutOwnerRepoCommitRoute: typeof LayoutOwnerRepoCommitRouteWithChildren
  LayoutOwnerRepoCommitsRoute: typeof LayoutOwnerRepoCommitsRouteWithChildren
  LayoutOwnerRepoForksRoute: typeof LayoutOwnerRepoForksRoute
  LayoutOwnerRepoIssuesRoute: typeof LayoutOwnerRepoIssuesRouteWithChildren
  LayoutOwnerRepoPullsRoute: typeof LayoutOwnerRepoPullsRouteWithChildren
  LayoutOwnerRepoReleasesRoute: typeof LayoutOwnerRepoReleasesRoute
  LayoutOwnerRepoSettingsRoute: typeof LayoutOwnerRepoSettingsRoute
  LayoutOwnerRepoStarsRoute: typeof LayoutOwnerRepoStarsRoute
  LayoutOwnerRepoWatchersRoute: typeof LayoutOwnerRepoWatchersRoute
  LayoutOwnerRepoIndexRoute: typeof LayoutOwnerRepoIndexRoute
  LayoutOwnerRepoBlameSplatRoute: typeof LayoutOwnerRepoBlameSplatRoute
  LayoutOwnerRepoSrcBranchBranchRoute: typeof LayoutOwnerRepoSrcBranchBranchRouteWithChildren
  LayoutOwnerRepoSrcCommitShaRoute: typeof LayoutOwnerRepoSrcCommitShaRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutExploreRoute: LayoutExploreRoute,
  LayoutRepositoriesRoute: LayoutRepositoriesRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProfileUsernameRoute: LayoutProfileUsernameRoute,
  LayoutOwnerRepoActivityRoute: LayoutOwnerRepoActivityRoute,
  LayoutOwnerRepoBranchesRoute: LayoutOwnerRepoBranchesRoute,
  LayoutOwnerRepoCommitRoute: LayoutOwnerRepoCommitRouteWithChildren,
  LayoutOwnerRepoCommitsRoute: LayoutOwnerRepoCommitsRouteWithChildren,
  LayoutOwnerRepoForksRoute: LayoutOwnerRepoForksRoute,
  LayoutOwnerRepoIssuesRoute: LayoutOwnerRepoIssuesRouteWithChildren,
  LayoutOwnerRepoPullsRoute: LayoutOwnerRepoPullsRouteWithChildren,
  LayoutOwnerRepoReleasesRoute: LayoutOwnerRepoReleasesRoute,
  LayoutOwnerRepoSettingsRoute: LayoutOwnerRepoSettingsRoute,
  LayoutOwnerRepoStarsRoute: LayoutOwnerRepoStarsRoute,
  LayoutOwnerRepoWatchersRoute: LayoutOwnerRepoWatchersRoute,
  LayoutOwnerRepoIndexRoute: LayoutOwnerRepoIndexRoute,
  LayoutOwnerRepoBlameSplatRoute: LayoutOwnerRepoBlameSplatRoute,
  LayoutOwnerRepoSrcBranchBranchRoute:
    LayoutOwnerRepoSrcBranchBranchRouteWithChildren,
  LayoutOwnerRepoSrcCommitShaRoute:
    LayoutOwnerRepoSrcCommitShaRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
