/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutExploreRouteImport } from './routes/_layout/explore'
import { Route as LayoutRepositoriesRouteImport } from './routes/_layout/repositories'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutProfileUsernameRouteImport } from './routes/_layout/profile.$username'
import { Route as LayoutOwnerRepoIndexRouteImport } from './routes/_layout/$owner/$repo/index'
import { Route as LayoutOwnerRepoActivityRouteImport } from './routes/_layout/$owner/$repo/activity'
import { Route as LayoutOwnerRepoBlobRouteImport } from './routes/_layout/$owner/$repo/blob'
import { Route as LayoutOwnerRepoBranchesRouteImport } from './routes/_layout/$owner/$repo/branches'
import { Route as LayoutOwnerRepoCommitsRouteImport } from './routes/_layout/$owner/$repo/commits'
import { Route as LayoutOwnerRepoForksRouteImport } from './routes/_layout/$owner/$repo/forks'
import { Route as LayoutOwnerRepoIssuesRouteImport } from './routes/_layout/$owner/$repo/issues'
import { Route as LayoutOwnerRepoPullsRouteImport } from './routes/_layout/$owner/$repo/pulls'
import { Route as LayoutOwnerRepoReleasesRouteImport } from './routes/_layout/$owner/$repo/releases'
import { Route as LayoutOwnerRepoStarsRouteImport } from './routes/_layout/$owner/$repo/stars'
import { Route as LayoutOwnerRepoWatchersRouteImport } from './routes/_layout/$owner/$repo/watchers'
import { Route as LayoutOwnerRepoCommitsIndexRouteImport } from './routes/_layout/$owner/$repo/commits.index'
import { Route as LayoutOwnerRepoCommitsHashRouteImport } from './routes/_layout/$owner/$repo/commits.$hash'
import { Route as LayoutOwnerRepoIssuesIndexRouteImport } from './routes/_layout/$owner/$repo/issues.index'
import { Route as LayoutOwnerRepoIssuesNumberRouteImport } from './routes/_layout/$owner/$repo/issues.$number'
import { Route as LayoutOwnerRepoIssuesNewRouteImport } from './routes/_layout/$owner/$repo/issues.new'
import { Route as LayoutOwnerRepoPullsIndexRouteImport } from './routes/_layout/$owner/$repo/pulls.index'
import { Route as LayoutOwnerRepoPullsNumberRouteImport } from './routes/_layout/$owner/$repo/pulls.$number'
import { Route as LayoutOwnerRepoPullsNewRouteImport } from './routes/_layout/$owner/$repo/pulls.new'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExploreRoute = LayoutExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRepositoriesRoute = LayoutRepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileUsernameRoute = LayoutProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnerRepoIndexRoute = LayoutOwnerRepoIndexRouteImport.update({
  id: '/$owner/$repo/',
  path: '/$owner/$repo/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnerRepoActivityRoute = LayoutOwnerRepoActivityRouteImport.update({
  id: '/$owner/$repo/activity',
  path: '/$owner/$repo/activity',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnerRepoBlobRoute = LayoutOwnerRepoBlobRouteImport.update({
  id: '/$owner/$repo/blob',
  path: '/$owner/$repo/blob',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnerRepoBranchesRoute = LayoutOwnerRepoBranchesRouteImport.update({
  id: '/$owner/$repo/branches',
  path: '/$owner/$repo/branches',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnerRepoCommitsRoute = LayoutOwnerRepoCommitsRouteImport.update({
  id: '/$owner/$repo/commits',
  path: '/$owner/$repo/commits',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnerRepoForksRoute = LayoutOwnerRepoForksRouteImport.update({
  id: '/$owner/$repo/forks',
  path: '/$owner/$repo/forks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnerRepoIssuesRoute = LayoutOwnerRepoIssuesRouteImport.update({
  id: '/$owner/$repo/issues',
  path: '/$owner/$repo/issues',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnerRepoPullsRoute = LayoutOwnerRepoPullsRouteImport.update({
  id: '/$owner/$repo/pulls',
  path: '/$owner/$repo/pulls',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnerRepoReleasesRoute = LayoutOwnerRepoReleasesRouteImport.update({
  id: '/$owner/$repo/releases',
  path: '/$owner/$repo/releases',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnerRepoStarsRoute = LayoutOwnerRepoStarsRouteImport.update({
  id: '/$owner/$repo/stars',
  path: '/$owner/$repo/stars',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnerRepoWatchersRoute = LayoutOwnerRepoWatchersRouteImport.update({
  id: '/$owner/$repo/watchers',
  path: '/$owner/$repo/watchers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOwnerRepoCommitsIndexRoute =
  LayoutOwnerRepoCommitsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutOwnerRepoCommitsRoute,
  } as any)
const LayoutOwnerRepoCommitsHashRoute =
  LayoutOwnerRepoCommitsHashRouteImport.update({
    id: '/$hash',
    path: '/$hash',
    getParentRoute: () => LayoutOwnerRepoCommitsRoute,
  } as any)
const LayoutOwnerRepoIssuesIndexRoute =
  LayoutOwnerRepoIssuesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutOwnerRepoIssuesRoute,
  } as any)
const LayoutOwnerRepoIssuesNumberRoute =
  LayoutOwnerRepoIssuesNumberRouteImport.update({
    id: '/$number',
    path: '/$number',
    getParentRoute: () => LayoutOwnerRepoIssuesRoute,
  } as any)
const LayoutOwnerRepoIssuesNewRoute =
  LayoutOwnerRepoIssuesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => LayoutOwnerRepoIssuesRoute,
  } as any)
const LayoutOwnerRepoPullsIndexRoute =
  LayoutOwnerRepoPullsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutOwnerRepoPullsRoute,
  } as any)
const LayoutOwnerRepoPullsNumberRoute =
  LayoutOwnerRepoPullsNumberRouteImport.update({
    id: '/$number',
    path: '/$number',
    getParentRoute: () => LayoutOwnerRepoPullsRoute,
  } as any)
const LayoutOwnerRepoPullsNewRoute = LayoutOwnerRepoPullsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LayoutOwnerRepoPullsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/explore': typeof LayoutExploreRoute
  '/repositories': typeof LayoutRepositoriesRoute
  '/settings': typeof LayoutSettingsRoute
  '/profile/$username': typeof LayoutProfileUsernameRoute
  '/$owner/$repo/activity': typeof LayoutOwnerRepoActivityRoute
  '/$owner/$repo/blob': typeof LayoutOwnerRepoBlobRoute
  '/$owner/$repo/branches': typeof LayoutOwnerRepoBranchesRoute
  '/$owner/$repo/commits': typeof LayoutOwnerRepoCommitsRouteWithChildren
  '/$owner/$repo/forks': typeof LayoutOwnerRepoForksRoute
  '/$owner/$repo/issues': typeof LayoutOwnerRepoIssuesRouteWithChildren
  '/$owner/$repo/pulls': typeof LayoutOwnerRepoPullsRouteWithChildren
  '/$owner/$repo/releases': typeof LayoutOwnerRepoReleasesRoute
  '/$owner/$repo/stars': typeof LayoutOwnerRepoStarsRoute
  '/$owner/$repo/watchers': typeof LayoutOwnerRepoWatchersRoute
  '/$owner/$repo/': typeof LayoutOwnerRepoIndexRoute
  '/$owner/$repo/commits/$hash': typeof LayoutOwnerRepoCommitsHashRoute
  '/$owner/$repo/issues/$number': typeof LayoutOwnerRepoIssuesNumberRoute
  '/$owner/$repo/issues/new': typeof LayoutOwnerRepoIssuesNewRoute
  '/$owner/$repo/pulls/$number': typeof LayoutOwnerRepoPullsNumberRoute
  '/$owner/$repo/pulls/new': typeof LayoutOwnerRepoPullsNewRoute
  '/$owner/$repo/commits/': typeof LayoutOwnerRepoCommitsIndexRoute
  '/$owner/$repo/issues/': typeof LayoutOwnerRepoIssuesIndexRoute
  '/$owner/$repo/pulls/': typeof LayoutOwnerRepoPullsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/explore': typeof LayoutExploreRoute
  '/repositories': typeof LayoutRepositoriesRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/profile/$username': typeof LayoutProfileUsernameRoute
  '/$owner/$repo/activity': typeof LayoutOwnerRepoActivityRoute
  '/$owner/$repo/blob': typeof LayoutOwnerRepoBlobRoute
  '/$owner/$repo/branches': typeof LayoutOwnerRepoBranchesRoute
  '/$owner/$repo/forks': typeof LayoutOwnerRepoForksRoute
  '/$owner/$repo/releases': typeof LayoutOwnerRepoReleasesRoute
  '/$owner/$repo/stars': typeof LayoutOwnerRepoStarsRoute
  '/$owner/$repo/watchers': typeof LayoutOwnerRepoWatchersRoute
  '/$owner/$repo': typeof LayoutOwnerRepoIndexRoute
  '/$owner/$repo/commits/$hash': typeof LayoutOwnerRepoCommitsHashRoute
  '/$owner/$repo/issues/$number': typeof LayoutOwnerRepoIssuesNumberRoute
  '/$owner/$repo/issues/new': typeof LayoutOwnerRepoIssuesNewRoute
  '/$owner/$repo/pulls/$number': typeof LayoutOwnerRepoPullsNumberRoute
  '/$owner/$repo/pulls/new': typeof LayoutOwnerRepoPullsNewRoute
  '/$owner/$repo/commits': typeof LayoutOwnerRepoCommitsIndexRoute
  '/$owner/$repo/issues': typeof LayoutOwnerRepoIssuesIndexRoute
  '/$owner/$repo/pulls': typeof LayoutOwnerRepoPullsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/explore': typeof LayoutExploreRoute
  '/_layout/repositories': typeof LayoutRepositoriesRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/profile/$username': typeof LayoutProfileUsernameRoute
  '/_layout/$owner/$repo/activity': typeof LayoutOwnerRepoActivityRoute
  '/_layout/$owner/$repo/blob': typeof LayoutOwnerRepoBlobRoute
  '/_layout/$owner/$repo/branches': typeof LayoutOwnerRepoBranchesRoute
  '/_layout/$owner/$repo/commits': typeof LayoutOwnerRepoCommitsRouteWithChildren
  '/_layout/$owner/$repo/forks': typeof LayoutOwnerRepoForksRoute
  '/_layout/$owner/$repo/issues': typeof LayoutOwnerRepoIssuesRouteWithChildren
  '/_layout/$owner/$repo/pulls': typeof LayoutOwnerRepoPullsRouteWithChildren
  '/_layout/$owner/$repo/releases': typeof LayoutOwnerRepoReleasesRoute
  '/_layout/$owner/$repo/stars': typeof LayoutOwnerRepoStarsRoute
  '/_layout/$owner/$repo/watchers': typeof LayoutOwnerRepoWatchersRoute
  '/_layout/$owner/$repo/': typeof LayoutOwnerRepoIndexRoute
  '/_layout/$owner/$repo/commits/$hash': typeof LayoutOwnerRepoCommitsHashRoute
  '/_layout/$owner/$repo/issues/$number': typeof LayoutOwnerRepoIssuesNumberRoute
  '/_layout/$owner/$repo/issues/new': typeof LayoutOwnerRepoIssuesNewRoute
  '/_layout/$owner/$repo/pulls/$number': typeof LayoutOwnerRepoPullsNumberRoute
  '/_layout/$owner/$repo/pulls/new': typeof LayoutOwnerRepoPullsNewRoute
  '/_layout/$owner/$repo/commits/': typeof LayoutOwnerRepoCommitsIndexRoute
  '/_layout/$owner/$repo/issues/': typeof LayoutOwnerRepoIssuesIndexRoute
  '/_layout/$owner/$repo/pulls/': typeof LayoutOwnerRepoPullsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/explore'
    | '/repositories'
    | '/settings'
    | '/profile/$username'
    | '/$owner/$repo/activity'
    | '/$owner/$repo/blob'
    | '/$owner/$repo/branches'
    | '/$owner/$repo/commits'
    | '/$owner/$repo/forks'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo/releases'
    | '/$owner/$repo/stars'
    | '/$owner/$repo/watchers'
    | '/$owner/$repo/'
    | '/$owner/$repo/commits/$hash'
    | '/$owner/$repo/issues/$number'
    | '/$owner/$repo/issues/new'
    | '/$owner/$repo/pulls/$number'
    | '/$owner/$repo/pulls/new'
    | '/$owner/$repo/commits/'
    | '/$owner/$repo/issues/'
    | '/$owner/$repo/pulls/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/explore'
    | '/repositories'
    | '/settings'
    | '/'
    | '/profile/$username'
    | '/$owner/$repo/activity'
    | '/$owner/$repo/blob'
    | '/$owner/$repo/branches'
    | '/$owner/$repo/forks'
    | '/$owner/$repo/releases'
    | '/$owner/$repo/stars'
    | '/$owner/$repo/watchers'
    | '/$owner/$repo'
    | '/$owner/$repo/commits/$hash'
    | '/$owner/$repo/issues/$number'
    | '/$owner/$repo/issues/new'
    | '/$owner/$repo/pulls/$number'
    | '/$owner/$repo/pulls/new'
    | '/$owner/$repo/commits'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pulls'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/explore'
    | '/_layout/repositories'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/profile/$username'
    | '/_layout/$owner/$repo/activity'
    | '/_layout/$owner/$repo/blob'
    | '/_layout/$owner/$repo/branches'
    | '/_layout/$owner/$repo/commits'
    | '/_layout/$owner/$repo/forks'
    | '/_layout/$owner/$repo/issues'
    | '/_layout/$owner/$repo/pulls'
    | '/_layout/$owner/$repo/releases'
    | '/_layout/$owner/$repo/stars'
    | '/_layout/$owner/$repo/watchers'
    | '/_layout/$owner/$repo/'
    | '/_layout/$owner/$repo/commits/$hash'
    | '/_layout/$owner/$repo/issues/$number'
    | '/_layout/$owner/$repo/issues/new'
    | '/_layout/$owner/$repo/pulls/$number'
    | '/_layout/$owner/$repo/pulls/new'
    | '/_layout/$owner/$repo/commits/'
    | '/_layout/$owner/$repo/issues/'
    | '/_layout/$owner/$repo/pulls/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/explore': {
      id: '/_layout/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof LayoutExploreRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/repositories': {
      id: '/_layout/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof LayoutRepositoriesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile/$username': {
      id: '/_layout/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof LayoutProfileUsernameRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/': {
      id: '/_layout/$owner/$repo/'
      path: '/$owner/$repo'
      fullPath: '/$owner/$repo/'
      preLoaderRoute: typeof LayoutOwnerRepoIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/activity': {
      id: '/_layout/$owner/$repo/activity'
      path: '/$owner/$repo/activity'
      fullPath: '/$owner/$repo/activity'
      preLoaderRoute: typeof LayoutOwnerRepoActivityRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/blob': {
      id: '/_layout/$owner/$repo/blob'
      path: '/$owner/$repo/blob'
      fullPath: '/$owner/$repo/blob'
      preLoaderRoute: typeof LayoutOwnerRepoBlobRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/branches': {
      id: '/_layout/$owner/$repo/branches'
      path: '/$owner/$repo/branches'
      fullPath: '/$owner/$repo/branches'
      preLoaderRoute: typeof LayoutOwnerRepoBranchesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/commits': {
      id: '/_layout/$owner/$repo/commits'
      path: '/$owner/$repo/commits'
      fullPath: '/$owner/$repo/commits'
      preLoaderRoute: typeof LayoutOwnerRepoCommitsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/forks': {
      id: '/_layout/$owner/$repo/forks'
      path: '/$owner/$repo/forks'
      fullPath: '/$owner/$repo/forks'
      preLoaderRoute: typeof LayoutOwnerRepoForksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/issues': {
      id: '/_layout/$owner/$repo/issues'
      path: '/$owner/$repo/issues'
      fullPath: '/$owner/$repo/issues'
      preLoaderRoute: typeof LayoutOwnerRepoIssuesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/pulls': {
      id: '/_layout/$owner/$repo/pulls'
      path: '/$owner/$repo/pulls'
      fullPath: '/$owner/$repo/pulls'
      preLoaderRoute: typeof LayoutOwnerRepoPullsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/releases': {
      id: '/_layout/$owner/$repo/releases'
      path: '/$owner/$repo/releases'
      fullPath: '/$owner/$repo/releases'
      preLoaderRoute: typeof LayoutOwnerRepoReleasesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/stars': {
      id: '/_layout/$owner/$repo/stars'
      path: '/$owner/$repo/stars'
      fullPath: '/$owner/$repo/stars'
      preLoaderRoute: typeof LayoutOwnerRepoStarsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/watchers': {
      id: '/_layout/$owner/$repo/watchers'
      path: '/$owner/$repo/watchers'
      fullPath: '/$owner/$repo/watchers'
      preLoaderRoute: typeof LayoutOwnerRepoWatchersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$owner/$repo/commits/': {
      id: '/_layout/$owner/$repo/commits/'
      path: '/'
      fullPath: '/$owner/$repo/commits/'
      preLoaderRoute: typeof LayoutOwnerRepoCommitsIndexRouteImport
      parentRoute: typeof LayoutOwnerRepoCommitsRoute
    }
    '/_layout/$owner/$repo/commits/$hash': {
      id: '/_layout/$owner/$repo/commits/$hash'
      path: '/$hash'
      fullPath: '/$owner/$repo/commits/$hash'
      preLoaderRoute: typeof LayoutOwnerRepoCommitsHashRouteImport
      parentRoute: typeof LayoutOwnerRepoCommitsRoute
    }
    '/_layout/$owner/$repo/issues/': {
      id: '/_layout/$owner/$repo/issues/'
      path: '/'
      fullPath: '/$owner/$repo/issues/'
      preLoaderRoute: typeof LayoutOwnerRepoIssuesIndexRouteImport
      parentRoute: typeof LayoutOwnerRepoIssuesRoute
    }
    '/_layout/$owner/$repo/issues/$number': {
      id: '/_layout/$owner/$repo/issues/$number'
      path: '/$number'
      fullPath: '/$owner/$repo/issues/$number'
      preLoaderRoute: typeof LayoutOwnerRepoIssuesNumberRouteImport
      parentRoute: typeof LayoutOwnerRepoIssuesRoute
    }
    '/_layout/$owner/$repo/issues/new': {
      id: '/_layout/$owner/$repo/issues/new'
      path: '/new'
      fullPath: '/$owner/$repo/issues/new'
      preLoaderRoute: typeof LayoutOwnerRepoIssuesNewRouteImport
      parentRoute: typeof LayoutOwnerRepoIssuesRoute
    }
    '/_layout/$owner/$repo/pulls/': {
      id: '/_layout/$owner/$repo/pulls/'
      path: '/'
      fullPath: '/$owner/$repo/pulls/'
      preLoaderRoute: typeof LayoutOwnerRepoPullsIndexRouteImport
      parentRoute: typeof LayoutOwnerRepoPullsRoute
    }
    '/_layout/$owner/$repo/pulls/$number': {
      id: '/_layout/$owner/$repo/pulls/$number'
      path: '/$number'
      fullPath: '/$owner/$repo/pulls/$number'
      preLoaderRoute: typeof LayoutOwnerRepoPullsNumberRouteImport
      parentRoute: typeof LayoutOwnerRepoPullsRoute
    }
    '/_layout/$owner/$repo/pulls/new': {
      id: '/_layout/$owner/$repo/pulls/new'
      path: '/new'
      fullPath: '/$owner/$repo/pulls/new'
      preLoaderRoute: typeof LayoutOwnerRepoPullsNewRouteImport
      parentRoute: typeof LayoutOwnerRepoPullsRoute
    }
  }
}

interface LayoutOwnerRepoCommitsRouteChildren {
  LayoutOwnerRepoCommitsHashRoute: typeof LayoutOwnerRepoCommitsHashRoute
  LayoutOwnerRepoCommitsIndexRoute: typeof LayoutOwnerRepoCommitsIndexRoute
}

const LayoutOwnerRepoCommitsRouteChildren: LayoutOwnerRepoCommitsRouteChildren =
  {
    LayoutOwnerRepoCommitsHashRoute: LayoutOwnerRepoCommitsHashRoute,
    LayoutOwnerRepoCommitsIndexRoute: LayoutOwnerRepoCommitsIndexRoute,
  }

const LayoutOwnerRepoCommitsRouteWithChildren =
  LayoutOwnerRepoCommitsRoute._addFileChildren(
    LayoutOwnerRepoCommitsRouteChildren,
  )

interface LayoutOwnerRepoIssuesRouteChildren {
  LayoutOwnerRepoIssuesNumberRoute: typeof LayoutOwnerRepoIssuesNumberRoute
  LayoutOwnerRepoIssuesNewRoute: typeof LayoutOwnerRepoIssuesNewRoute
  LayoutOwnerRepoIssuesIndexRoute: typeof LayoutOwnerRepoIssuesIndexRoute
}

const LayoutOwnerRepoIssuesRouteChildren: LayoutOwnerRepoIssuesRouteChildren = {
  LayoutOwnerRepoIssuesNumberRoute: LayoutOwnerRepoIssuesNumberRoute,
  LayoutOwnerRepoIssuesNewRoute: LayoutOwnerRepoIssuesNewRoute,
  LayoutOwnerRepoIssuesIndexRoute: LayoutOwnerRepoIssuesIndexRoute,
}

const LayoutOwnerRepoIssuesRouteWithChildren =
  LayoutOwnerRepoIssuesRoute._addFileChildren(
    LayoutOwnerRepoIssuesRouteChildren,
  )

interface LayoutOwnerRepoPullsRouteChildren {
  LayoutOwnerRepoPullsNumberRoute: typeof LayoutOwnerRepoPullsNumberRoute
  LayoutOwnerRepoPullsNewRoute: typeof LayoutOwnerRepoPullsNewRoute
  LayoutOwnerRepoPullsIndexRoute: typeof LayoutOwnerRepoPullsIndexRoute
}

const LayoutOwnerRepoPullsRouteChildren: LayoutOwnerRepoPullsRouteChildren = {
  LayoutOwnerRepoPullsNumberRoute: LayoutOwnerRepoPullsNumberRoute,
  LayoutOwnerRepoPullsNewRoute: LayoutOwnerRepoPullsNewRoute,
  LayoutOwnerRepoPullsIndexRoute: LayoutOwnerRepoPullsIndexRoute,
}

const LayoutOwnerRepoPullsRouteWithChildren =
  LayoutOwnerRepoPullsRoute._addFileChildren(LayoutOwnerRepoPullsRouteChildren)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutExploreRoute: typeof LayoutExploreRoute
  LayoutRepositoriesRoute: typeof LayoutRepositoriesRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProfileUsernameRoute: typeof LayoutProfileUsernameRoute
  LayoutOwnerRepoActivityRoute: typeof LayoutOwnerRepoActivityRoute
  LayoutOwnerRepoBlobRoute: typeof LayoutOwnerRepoBlobRoute
  LayoutOwnerRepoBranchesRoute: typeof LayoutOwnerRepoBranchesRoute
  LayoutOwnerRepoCommitsRoute: typeof LayoutOwnerRepoCommitsRouteWithChildren
  LayoutOwnerRepoForksRoute: typeof LayoutOwnerRepoForksRoute
  LayoutOwnerRepoIssuesRoute: typeof LayoutOwnerRepoIssuesRouteWithChildren
  LayoutOwnerRepoPullsRoute: typeof LayoutOwnerRepoPullsRouteWithChildren
  LayoutOwnerRepoReleasesRoute: typeof LayoutOwnerRepoReleasesRoute
  LayoutOwnerRepoStarsRoute: typeof LayoutOwnerRepoStarsRoute
  LayoutOwnerRepoWatchersRoute: typeof LayoutOwnerRepoWatchersRoute
  LayoutOwnerRepoIndexRoute: typeof LayoutOwnerRepoIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutExploreRoute: LayoutExploreRoute,
  LayoutRepositoriesRoute: LayoutRepositoriesRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProfileUsernameRoute: LayoutProfileUsernameRoute,
  LayoutOwnerRepoActivityRoute: LayoutOwnerRepoActivityRoute,
  LayoutOwnerRepoBlobRoute: LayoutOwnerRepoBlobRoute,
  LayoutOwnerRepoBranchesRoute: LayoutOwnerRepoBranchesRoute,
  LayoutOwnerRepoCommitsRoute: LayoutOwnerRepoCommitsRouteWithChildren,
  LayoutOwnerRepoForksRoute: LayoutOwnerRepoForksRoute,
  LayoutOwnerRepoIssuesRoute: LayoutOwnerRepoIssuesRouteWithChildren,
  LayoutOwnerRepoPullsRoute: LayoutOwnerRepoPullsRouteWithChildren,
  LayoutOwnerRepoReleasesRoute: LayoutOwnerRepoReleasesRoute,
  LayoutOwnerRepoStarsRoute: LayoutOwnerRepoStarsRoute,
  LayoutOwnerRepoWatchersRoute: LayoutOwnerRepoWatchersRoute,
  LayoutOwnerRepoIndexRoute: LayoutOwnerRepoIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
