"""add principals and require usernames

Revision ID: 341dbd85e529
Revises: 2f2790e2f5e6
Create Date: 2026-10-06 23:36:18.404096

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "341dbd85e529"
down_revision: str | None = "2f2790e2f5e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()

    # Backfill missing usernames from the email local part, avoiding collisions.
    missing = bind.execute(sa.text("SELECT id, email FROM \"user\" WHERE username IS NULL OR username = ''")).fetchall()
    taken = {
        row[0]
        for row in bind.execute(
            sa.text("SELECT username FROM \"user\" WHERE username IS NOT NULL AND username <> ''")
        ).fetchall()
    }
    for user_id, email in missing:
        base = (email or "").split("@", 1)[0] or "user"
        candidate = base
        suffix = 1
        while candidate in taken:
            candidate = f"{base}-{suffix}"
            suffix += 1
        taken.add(candidate)
        bind.execute(
            sa.text('UPDATE "user" SET username = :username WHERE id = :id'),
            {"username": candidate, "id": user_id},
        )

    default_user = bind.execute(
        sa.text('SELECT id FROM "user" ORDER BY is_superuser DESC, created_at LIMIT 1')
    ).scalar()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "principal",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("lower_name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("principal_pkey")),
    )
    op.create_index(op.f("principal_lower_name_idx"), "principal", ["lower_name"], unique=True)
    op.create_table(
        "organization",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["principal.id"], name=op.f("organization_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("organization_pkey")),
    )

    # Every user becomes a principal.
    bind.execute(
        sa.text(
            "INSERT INTO principal (id, name, lower_name, display_name, type, created_at, updated_at) "
            "SELECT id, username, lower(username), full_name, 'user', created_at, updated_at FROM \"user\""
        )
    )

    # Activity, comments and issues are linked to a user instead of an email.
    bind.execute(
        sa.text(
            'UPDATE activity a SET actor_id = u.id FROM "user" u WHERE a.actor_id IS NULL AND a.actor_email = u.email'
        )
    )
    if default_user is not None:
        bind.execute(sa.text("UPDATE activity SET actor_id = :user WHERE actor_id IS NULL"), {"user": default_user})
    op.alter_column("activity", "actor_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("activity", "actor_email")
    bind.execute(
        sa.text(
            'UPDATE comment c SET author_id = u.id FROM "user" u WHERE c.author_id IS NULL AND c.author_email = u.email'
        )
    )
    if default_user is not None:
        bind.execute(sa.text("UPDATE comment SET author_id = :user WHERE author_id IS NULL"), {"user": default_user})
    op.alter_column("comment", "author_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("comment", "author_email")
    op.add_column("issue", sa.Column("author_id", sa.UUID(), nullable=True))
    bind.execute(sa.text('UPDATE issue i SET author_id = u.id FROM "user" u WHERE i.author_email = u.email'))
    if default_user is not None:
        bind.execute(sa.text("UPDATE issue SET author_id = :user WHERE author_id IS NULL"), {"user": default_user})
    op.alter_column("issue", "author_id", existing_type=sa.UUID(), nullable=False)
    op.create_index(op.f("issue_author_id_idx"), "issue", ["author_id"], unique=False)
    op.create_foreign_key(op.f("issue_author_id_fkey"), "issue", "user", ["author_id"], ["id"])
    op.drop_column("issue", "author_email")

    # Repositories are owned by a principal (user or organization).
    for repo_id, path, owner_id in bind.execute(sa.text("SELECT id, path, owner_id FROM repository")).fetchall():
        resolved = owner_id
        if resolved is None and path:
            owner_name = path.split("/", 1)[0] if "/" in path else None
            if owner_name:
                resolved = bind.execute(
                    sa.text("SELECT id FROM principal WHERE lower_name = lower(:name)"),
                    {"name": owner_name},
                ).scalar()
        if resolved is None:
            resolved = default_user
        if resolved is not None:
            bind.execute(
                sa.text("UPDATE repository SET owner_id = :owner WHERE id = :id"),
                {"owner": resolved, "id": repo_id},
            )
    op.alter_column("repository", "owner_id", existing_type=sa.UUID(), nullable=False)
    op.drop_index(op.f("repository_path_idx"), table_name="repository")
    op.create_unique_constraint("repository_owner_name_key", "repository", ["owner_id", "name"])
    op.drop_constraint(op.f("repository_owner_id_fkey"), "repository", type_="foreignkey")
    op.create_foreign_key(op.f("repository_owner_id_fkey"), "repository", "principal", ["owner_id"], ["id"])
    op.drop_column("repository", "path")

    op.create_foreign_key(op.f("user_id_fkey"), "user", "principal", ["id"], ["id"])
    op.drop_index(op.f("user_username_idx"), table_name="user")
    op.drop_column("user", "username")
    op.drop_column("user", "updated_at")
    op.drop_column("user", "created_at")
    op.drop_column("user", "full_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("full_name", sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column(
        "user",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "user", sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.add_column("user", sa.Column("username", sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.execute(
        sa.text(
            'UPDATE "user" u SET username = p.name, full_name = p.display_name, '
            "created_at = p.created_at, updated_at = p.updated_at FROM principal p WHERE p.id = u.id"
        )
    )
    op.drop_constraint(op.f("user_id_fkey"), "user", type_="foreignkey")
    op.create_index(op.f("user_username_idx"), "user", ["username"], unique=True)
    op.add_column("repository", sa.Column("path", sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_constraint(op.f("repository_owner_id_fkey"), "repository", type_="foreignkey")
    op.create_foreign_key(op.f("repository_owner_id_fkey"), "repository", "user", ["owner_id"], ["id"])
    op.drop_constraint("repository_owner_name_key", "repository", type_="unique")
    op.create_index(op.f("repository_path_idx"), "repository", ["path"], unique=True)
    op.alter_column("repository", "owner_id", existing_type=sa.UUID(), nullable=True)
    op.add_column("issue", sa.Column("author_email", sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(op.f("issue_author_id_fkey"), "issue", type_="foreignkey")
    op.drop_index(op.f("issue_author_id_idx"), table_name="issue")
    op.drop_column("issue", "author_id")
    op.add_column("comment", sa.Column("author_email", sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column("comment", "author_id", existing_type=sa.UUID(), nullable=True)
    op.add_column("activity", sa.Column("actor_email", sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column("activity", "actor_id", existing_type=sa.UUID(), nullable=True)
    op.drop_table("organization")
    op.drop_index(op.f("principal_lower_name_idx"), table_name="principal")
    op.drop_table("principal")
    # ### end Alembic commands ###
