"""add stars watchers comments releases activity

Revision ID: 59b4e06c1214
Revises: 7f8c9a0b1d2e
Create Date: 2026-10-04 15:43:31.852390

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "59b4e06c1214"
down_revision: str | None = "7f8c9a0b1d2e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity",
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_email", sa.String(length=255), nullable=True),
        sa.Column("repo_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("target_type", sa.String(length=40), nullable=True),
        sa.Column("target_number", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["actor_id"], ["user.id"], name=op.f("activity_actor_id_fkey")),
        sa.ForeignKeyConstraint(["repo_id"], ["repository.id"], name=op.f("activity_repo_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("activity_pkey")),
    )
    op.create_index(op.f("activity_actor_id_idx"), "activity", ["actor_id"], unique=False)
    op.create_index(op.f("activity_repo_id_idx"), "activity", ["repo_id"], unique=False)
    op.create_table(
        "release",
        sa.Column("repo_id", sa.UUID(), nullable=False),
        sa.Column("tag_name", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("author_id", sa.UUID(), nullable=True),
        sa.Column("target_commitish", sa.String(length=255), nullable=False),
        sa.Column("is_draft", sa.Boolean(), nullable=False),
        sa.Column("is_prerelease", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["author_id"], ["user.id"], name=op.f("release_author_id_fkey")),
        sa.ForeignKeyConstraint(["repo_id"], ["repository.id"], name=op.f("release_repo_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("release_pkey")),
        sa.UniqueConstraint("repo_id", "tag_name", name="release_repo_tag_key"),
    )
    op.create_index(op.f("release_author_id_idx"), "release", ["author_id"], unique=False)
    op.create_index(op.f("release_repo_id_idx"), "release", ["repo_id"], unique=False)
    op.create_table(
        "star",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("repo_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["repo_id"], ["repository.id"], name=op.f("star_repo_id_fkey")),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("star_user_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("star_pkey")),
        sa.UniqueConstraint("user_id", "repo_id", name="star_user_repo_key"),
    )
    op.create_index(op.f("star_repo_id_idx"), "star", ["repo_id"], unique=False)
    op.create_index(op.f("star_user_id_idx"), "star", ["user_id"], unique=False)
    op.create_table(
        "watcher",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("repo_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["repo_id"], ["repository.id"], name=op.f("watcher_repo_id_fkey")),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("watcher_user_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("watcher_pkey")),
        sa.UniqueConstraint("user_id", "repo_id", name="watcher_user_repo_key"),
    )
    op.create_index(op.f("watcher_repo_id_idx"), "watcher", ["repo_id"], unique=False)
    op.create_index(op.f("watcher_user_id_idx"), "watcher", ["user_id"], unique=False)
    op.create_table(
        "comment",
        sa.Column("issue_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=True),
        sa.Column("author_email", sa.String(length=255), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["author_id"], ["user.id"], name=op.f("comment_author_id_fkey")),
        sa.ForeignKeyConstraint(["issue_id"], ["issue.id"], name=op.f("comment_issue_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("comment_pkey")),
    )
    op.create_index(op.f("comment_author_id_idx"), "comment", ["author_id"], unique=False)
    op.create_index(op.f("comment_issue_id_idx"), "comment", ["issue_id"], unique=False)
    op.add_column("repository", sa.Column("fork_of_id", sa.UUID(), nullable=True))
    op.create_index(op.f("repository_fork_of_id_idx"), "repository", ["fork_of_id"], unique=False)
    op.create_foreign_key(op.f("repository_fork_of_id_fkey"), "repository", "repository", ["fork_of_id"], ["id"])
    op.add_column("user", sa.Column("username", sa.String(length=255), nullable=True))
    op.create_index(op.f("user_username_idx"), "user", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("user_username_idx"), table_name="user")
    op.drop_column("user", "username")
    op.drop_constraint(op.f("repository_fork_of_id_fkey"), "repository", type_="foreignkey")
    op.drop_index(op.f("repository_fork_of_id_idx"), table_name="repository")
    op.drop_column("repository", "fork_of_id")
    op.drop_index(op.f("comment_issue_id_idx"), table_name="comment")
    op.drop_index(op.f("comment_author_id_idx"), table_name="comment")
    op.drop_table("comment")
    op.drop_index(op.f("watcher_user_id_idx"), table_name="watcher")
    op.drop_index(op.f("watcher_repo_id_idx"), table_name="watcher")
    op.drop_table("watcher")
    op.drop_index(op.f("star_user_id_idx"), table_name="star")
    op.drop_index(op.f("star_repo_id_idx"), table_name="star")
    op.drop_table("star")
    op.drop_index(op.f("release_repo_id_idx"), table_name="release")
    op.drop_index(op.f("release_author_id_idx"), table_name="release")
    op.drop_table("release")
    op.drop_index(op.f("activity_repo_id_idx"), table_name="activity")
    op.drop_index(op.f("activity_actor_id_idx"), table_name="activity")
    op.drop_table("activity")
    # ### end Alembic commands ###
