"""drop repository star and fork count columns

Revision ID: 2f2790e2f5e6
Revises: 59b4e06c1214
Create Date: 2026-10-05 21:27:33.663641

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f2790e2f5e6"
down_revision: str | None = "59b4e06c1214"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("repository", "stars_count")
    op.drop_column("repository", "forks_count")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("repository", sa.Column("forks_count", sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column("repository", sa.Column("stars_count", sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
