"""make timestamps and release author non-null

Revision ID: b797260762a2
Revises: 341dbd85e529
Create Date: 2026-10-07 22:29:30.055525

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b797260762a2"
down_revision: str | None = "341dbd85e529"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Backfill existing NULL values before enforcing NOT NULL on the columns.
    connection = op.get_bind()
    for table in ("activity", "comment", "issue", "principal", "release", "repository", "star", "watcher"):
        connection.execute(sa.text(f"UPDATE {table} SET updated_at = created_at WHERE updated_at IS NULL"))
    connection.execute(
        sa.text(
            'UPDATE release SET author_id = (SELECT id FROM "user" ORDER BY created_at LIMIT 1) WHERE author_id IS NULL'
        )
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "activity",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        nullable=False,
    )
    op.alter_column(
        "comment",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        nullable=False,
    )
    op.alter_column("issue", "type", existing_type=sa.VARCHAR(length=20), server_default=None, existing_nullable=False)
    op.alter_column(
        "issue",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        nullable=False,
    )
    op.alter_column(
        "principal",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        nullable=False,
    )
    op.alter_column(
        "pull_request",
        "base_branch",
        existing_type=sa.VARCHAR(length=255),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "pull_request", "has_merged", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False
    )
    op.alter_column("release", "author_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column(
        "release",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        nullable=False,
    )
    op.alter_column(
        "repository",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        nullable=False,
    )
    op.alter_column(
        "star",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        nullable=False,
    )
    op.alter_column(
        "watcher",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "watcher", "updated_at", existing_type=postgresql.TIMESTAMP(timezone=True), server_default=None, nullable=True
    )
    op.alter_column(
        "star", "updated_at", existing_type=postgresql.TIMESTAMP(timezone=True), server_default=None, nullable=True
    )
    op.alter_column(
        "repository",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        nullable=True,
    )
    op.alter_column(
        "release", "updated_at", existing_type=postgresql.TIMESTAMP(timezone=True), server_default=None, nullable=True
    )
    op.alter_column("release", "author_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column(
        "pull_request",
        "has_merged",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "pull_request",
        "base_branch",
        existing_type=sa.VARCHAR(length=255),
        server_default=sa.text("'main'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "principal", "updated_at", existing_type=postgresql.TIMESTAMP(timezone=True), server_default=None, nullable=True
    )
    op.alter_column(
        "issue", "updated_at", existing_type=postgresql.TIMESTAMP(timezone=True), server_default=None, nullable=True
    )
    op.alter_column(
        "issue",
        "type",
        existing_type=sa.VARCHAR(length=20),
        server_default=sa.text("'issue'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "comment", "updated_at", existing_type=postgresql.TIMESTAMP(timezone=True), server_default=None, nullable=True
    )
    op.alter_column(
        "activity", "updated_at", existing_type=postgresql.TIMESTAMP(timezone=True), server_default=None, nullable=True
    )
    # ### end Alembic commands ###
